//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassicUO.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResOptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResOptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClassicUO.Resources.ResOptions", typeof(ResOptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combat-Spells.
        /// </summary>
        internal static string Btn_CombatSpells {
            get {
                return ResourceManager.GetString("Btn_CombatSpells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Containers.
        /// </summary>
        internal static string Btn_Containers {
            get {
                return ResourceManager.GetString("Btn_Containers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counters.
        /// </summary>
        internal static string Btn_Counters {
            get {
                return ResourceManager.GetString("Btn_Counters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experimental.
        /// </summary>
        internal static string Btn_Experimental {
            get {
                return ResourceManager.GetString("Btn_Experimental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonts.
        /// </summary>
        internal static string Btn_Fonts {
            get {
                return ResourceManager.GetString("Btn_Fonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string Btn_General {
            get {
                return ResourceManager.GetString("Btn_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info Bar.
        /// </summary>
        internal static string Btn_InfoBar {
            get {
                return ResourceManager.GetString("Btn_InfoBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macros.
        /// </summary>
        internal static string Btn_Macros {
            get {
                return ResourceManager.GetString("Btn_Macros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound.
        /// </summary>
        internal static string Btn_Sound {
            get {
                return ResourceManager.GetString("Btn_Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech.
        /// </summary>
        internal static string Btn_Speech {
            get {
                return ResourceManager.GetString("Btn_Speech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip.
        /// </summary>
        internal static string Btn_Tooltip {
            get {
                return ResourceManager.GetString("Btn_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        internal static string Btn_Video {
            get {
                return ResourceManager.GetString("Btn_Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold ALT key + right click to close Anchored gumps.
        /// </summary>
        internal static string Chk_AltCloseGumps {
            get {
                return ResourceManager.GetString("Chk_AltCloseGumps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold ALT key to move gumps.
        /// </summary>
        internal static string Chk_AltMoveGumps {
            get {
                return ResourceManager.GetString("Chk_AltMoveGumps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always run.
        /// </summary>
        internal static string Chk_AlwaysRun {
            get {
                return ResourceManager.GetString("Chk_AlwaysRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unless hidden.
        /// </summary>
        internal static string Chk_AlwaysRunHidden {
            get {
                return ResourceManager.GetString("Chk_AlwaysRunHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Open Corpses.
        /// </summary>
        internal static string Chk_AutoOpenCorpses {
            get {
                return ResourceManager.GetString("Chk_AutoOpenCorpses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Open Doors.
        /// </summary>
        internal static string Chk_AutoOpenDoors {
            get {
                return ResourceManager.GetString("Chk_AutoOpenDoors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full.
        /// </summary>
        internal static string Chk_CircleTransType_Full {
            get {
                return ResourceManager.GetString("Chk_CircleTransType_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gradient.
        /// </summary>
        internal static string Chk_CircleTransType_Gradient {
            get {
                return ResourceManager.GetString("Chk_CircleTransType_Gradient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close all Anchored gumps when right click on a group.
        /// </summary>
        internal static string Chk_ClickCloseAllGumps {
            get {
                return ResourceManager.GetString("Chk_ClickCloseAllGumps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both.
        /// </summary>
        internal static string Chk_CorpseOpt_Both {
            get {
                return ResourceManager.GetString("Chk_CorpseOpt_Both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string Chk_CorpseOpt_None {
            get {
                return ResourceManager.GetString("Chk_CorpseOpt_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Hiding.
        /// </summary>
        internal static string Chk_CorpseOpt_NotHid {
            get {
                return ResourceManager.GetString("Chk_CorpseOpt_NotHid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Targeting.
        /// </summary>
        internal static string Chk_CorpseOpt_NotTar {
            get {
                return ResourceManager.GetString("Chk_CorpseOpt_NotTar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable the Menu Bar.
        /// </summary>
        internal static string Chk_DisableMenu {
            get {
                return ResourceManager.GetString("Chk_DisableMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select humanoids only.
        /// </summary>
        internal static string Chk_DragHumanoidsOnly {
            get {
                return ResourceManager.GetString("Chk_DragHumanoidsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable circle of transparency.
        /// </summary>
        internal static string Chk_EnableCircleTrans {
            get {
                return ResourceManager.GetString("Chk_EnableCircleTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable drag-select to open health bars.
        /// </summary>
        internal static string Chk_EnableDragHPBars {
            get {
                return ResourceManager.GetString("Chk_EnableDragHPBars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable pathfinding.
        /// </summary>
        internal static string Chk_EnablePathfinding {
            get {
                return ResourceManager.GetString("Chk_EnablePathfinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce FPS when game is inactive.
        /// </summary>
        internal static string Chk_FPSInactive {
            get {
                return ResourceManager.GetString("Chk_FPSInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both.
        /// </summary>
        internal static string Chk_GridLoot_Both {
            get {
                return ResourceManager.GetString("Chk_GridLoot_Both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid loot only.
        /// </summary>
        internal static string Chk_GridLoot_GridOnly {
            get {
                return ResourceManager.GetString("Chk_GridLoot_GridOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string Chk_GridLoot_None {
            get {
                return ResourceManager.GetString("Chk_GridLoot_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide roof tiles.
        /// </summary>
        internal static string Chk_HideRoofTiles {
            get {
                return ResourceManager.GetString("Chk_HideRoofTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide vegetation.
        /// </summary>
        internal static string Chk_HideVegetation {
            get {
                return ResourceManager.GetString("Chk_HideVegetation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight by state (poisoned, yellow hits, paralyzed).
        /// </summary>
        internal static string Chk_HighlighState {
            get {
                return ResourceManager.GetString("Chk_HighlighState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight game objects.
        /// </summary>
        internal static string Chk_HighlightObjects {
            get {
                return ResourceManager.GetString("Chk_HighlightObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both.
        /// </summary>
        internal static string Chk_HP_Both {
            get {
                return ResourceManager.GetString("Chk_HP_Both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string Chk_HP_Line {
            get {
                return ResourceManager.GetString("Chk_HP_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage.
        /// </summary>
        internal static string Chk_HP_Percentage {
            get {
                return ResourceManager.GetString("Chk_HP_Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal fields.
        /// </summary>
        internal static string Chk_HPFields_Normal {
            get {
                return ResourceManager.GetString("Chk_HPFields_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static fields.
        /// </summary>
        internal static string Chk_HPFields_Static {
            get {
                return ResourceManager.GetString("Chk_HPFields_Static", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile fields.
        /// </summary>
        internal static string Chk_HPFields_Tile {
            get {
                return ResourceManager.GetString("Chk_HPFields_Tile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always.
        /// </summary>
        internal static string Chk_HPShow_Always {
            get {
                return ResourceManager.GetString("Chk_HPShow_Always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less than 100 %.
        /// </summary>
        internal static string Chk_HPShow_Less {
            get {
                return ResourceManager.GetString("Chk_HPShow_Less", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart.
        /// </summary>
        internal static string Chk_HPShow_Smart {
            get {
                return ResourceManager.GetString("Chk_HPShow_Smart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile is dead.
        /// </summary>
        internal static string Chk_HPType_MobileDead {
            get {
                return ResourceManager.GetString("Chk_HPType_MobileDead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile out of range.
        /// </summary>
        internal static string Chk_HPType_MobileOOR {
            get {
                return ResourceManager.GetString("Chk_HPType_MobileOOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string Chk_HPType_None {
            get {
                return ResourceManager.GetString("Chk_HPType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invulnerable Color.
        /// </summary>
        internal static string Chk_InvulColor {
            get {
                return ResourceManager.GetString("Chk_InvulColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl.
        /// </summary>
        internal static string Chk_KeyMod_Ctrl {
            get {
                return ResourceManager.GetString("Chk_KeyMod_Ctrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string Chk_KeyMod_None {
            get {
                return ResourceManager.GetString("Chk_KeyMod_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        internal static string Chk_KeyMod_Shift {
            get {
                return ResourceManager.GetString("Chk_KeyMod_Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark cave tiles.
        /// </summary>
        internal static string Chk_MarkCaveTiles {
            get {
                return ResourceManager.GetString("Chk_MarkCaveTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects alpha fading.
        /// </summary>
        internal static string Chk_ObjAlphaFading {
            get {
                return ResourceManager.GetString("Chk_ObjAlphaFading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No color for object out of range.
        /// </summary>
        internal static string Chk_OutOfRangeColor {
            get {
                return ResourceManager.GetString("Chk_OutOfRangeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paralyzed Color.
        /// </summary>
        internal static string Chk_ParalyzedColor {
            get {
                return ResourceManager.GetString("Chk_ParalyzedColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poisoned Color.
        /// </summary>
        internal static string Chk_PoisonedColor {
            get {
                return ResourceManager.GetString("Chk_PoisonedColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sallos easy grab.
        /// </summary>
        internal static string Chk_SallosEasyGrab {
            get {
                return ResourceManager.GetString("Chk_SallosEasyGrab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save healthbars on logout.
        /// </summary>
        internal static string Chk_SaveHPBarsOnLogout {
            get {
                return ResourceManager.GetString("Chk_SaveHPBarsOnLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold Shift for Context Menus.
        /// </summary>
        internal static string Chk_ShiftContext {
            get {
                return ResourceManager.GetString("Chk_ShiftContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use SHIFT for pathfinding.
        /// </summary>
        internal static string Chk_ShiftPathfinding {
            get {
                return ResourceManager.GetString("Chk_ShiftPathfinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold Shift to split stack of items.
        /// </summary>
        internal static string Chk_ShiftStack {
            get {
                return ResourceManager.GetString("Chk_ShiftStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show gump for party invites.
        /// </summary>
        internal static string Chk_ShowGumpPartyInv {
            get {
                return ResourceManager.GetString("Chk_ShowGumpPartyInv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show houses content.
        /// </summary>
        internal static string Chk_ShowHousesContent {
            get {
                return ResourceManager.GetString("Chk_ShowHousesContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show HP.
        /// </summary>
        internal static string Chk_ShowHP {
            get {
                return ResourceManager.GetString("Chk_ShowHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show incoming new corpses.
        /// </summary>
        internal static string Chk_ShowIncCorpses {
            get {
                return ResourceManager.GetString("Chk_ShowIncCorpses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show incoming new mobiles.
        /// </summary>
        internal static string Chk_ShowIncMobiles {
            get {
                return ResourceManager.GetString("Chk_ShowIncMobiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show target range indicator.
        /// </summary>
        internal static string Chk_ShowTarRangeIndic {
            get {
                return ResourceManager.GetString("Chk_ShowTarRangeIndic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip empty corpses.
        /// </summary>
        internal static string Chk_SkipEmptyCorpses {
            get {
                return ResourceManager.GetString("Chk_SkipEmptyCorpses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smooth boat movements.
        /// </summary>
        internal static string Chk_SmoothBoat {
            get {
                return ResourceManager.GetString("Chk_SmoothBoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smooth doors.
        /// </summary>
        internal static string Chk_SmoothDoors {
            get {
                return ResourceManager.GetString("Chk_SmoothDoors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use standard skills gump.
        /// </summary>
        internal static string Chk_StandardSkillGump {
            get {
                return ResourceManager.GetString("Chk_StandardSkillGump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold TAB key for combat.
        /// </summary>
        internal static string Chk_TabCombat {
            get {
                return ResourceManager.GetString("Chk_TabCombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text alpha fading.
        /// </summary>
        internal static string Chk_TextAlphaFading {
            get {
                return ResourceManager.GetString("Chk_TextAlphaFading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trees to stumps.
        /// </summary>
        internal static string Chk_TreesStumps {
            get {
                return ResourceManager.GetString("Chk_TreesStumps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use All Black Backgrounds.
        /// </summary>
        internal static string Chk_UseBlackBackgr {
            get {
                return ResourceManager.GetString("Chk_UseBlackBackgr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Custom Health Bars.
        /// </summary>
        internal static string Chk_UseCustomHPBars {
            get {
                return ResourceManager.GetString("Chk_UseCustomHPBars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparency type:.
        /// </summary>
        internal static string Lb_CircleTransType {
            get {
                return ResourceManager.GetString("Lb_CircleTransType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close healthbar gump when:.
        /// </summary>
        internal static string Lb_CloseHPGumpWhen {
            get {
                return ResourceManager.GetString("Lb_CloseHPGumpWhen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corpse Open Options:.
        /// </summary>
        internal static string Lb_CorpseOpenOptions {
            get {
                return ResourceManager.GetString("Lb_CorpseOpenOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corpse Open Range:.
        /// </summary>
        internal static string Lb_CorpseOpenRange {
            get {
                return ResourceManager.GetString("Lb_CorpseOpenRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag-select modifier key.
        /// </summary>
        internal static string Lb_DragKey {
            get {
                return ResourceManager.GetString("Lb_DragKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - FPS:.
        /// </summary>
        internal static string Lb_FPS {
            get {
                return ResourceManager.GetString("Lb_FPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid loot.
        /// </summary>
        internal static string Lb_GridLoot {
            get {
                return ResourceManager.GetString("Lb_GridLoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mode:.
        /// </summary>
        internal static string Lb_HP_Mode {
            get {
                return ResourceManager.GetString("Lb_HP_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields: .
        /// </summary>
        internal static string Lb_HPFields {
            get {
                return ResourceManager.GetString("Lb_HPFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop Gump Size (multiple of 60):.
        /// </summary>
        internal static string Lb_ShopGumpSize {
            get {
                return ResourceManager.GetString("Lb_ShopGumpSize", resourceCulture);
            }
        }
    }
}
