<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\external\FNA\FNA.Core.csproj" />
    <ProjectReference Include="..\ClassicUO.Agent.Contracts\ClassicUO.Agent.Contracts.csproj" />
  </ItemGroup>

</Project>
