namespace ClassicUO.Ecs;

// Ported from ClassicUO.Client/Game/Data/SpellsMastery.cs — data only (group/index helpers omitted).
internal static class MasterySpellData
{
    public static readonly string[] Names =
    {
        "Inspire",
        "Invigorate",
        "Resilience",
        "Perseverance",
        "Tribulation",
        "Despair",
        "Death Ray",
        "Ethereal Burst",
        "Nether Blast",
        "Mystic Weapon",
        "Command Undead",
        "Conduit",
        "Mana Shield",
        "Summon Reaper",
        "Enchanted Summoning",
        "Anticipate Hit",
        "Warcry",
        "Intuition",
        "Rejuvenate",
        "Holy Fist",
        "Shadow",
        "White Tiger Form",
        "Flaming Shot",
        "Playing The Odds",
        "Thrust",
        "Pierce",
        "Stagger",
        "Toughness",
        "Onslaught",
        "Focused Eye",
        "Elemental Fury",
        "Called Shot",
        "Warrior's Gifts",
        "Shield Bash",
        "Bodyguard",
        "Heighten Senses",
        "Tolerance",
        "Injected Strike",
        "Potency",
        "Rampage",
        "Fists of Fury",
        "Knockout",
        "Whispering",
        "Combat Training",
        "Boarding",
    };

    public static readonly int[] Ids =
    {
        701,
        702,
        703,
        704,
        705,
        706,
        707,
        708,
        709,
        710,
        711,
        712,
        713,
        714,
        715,
        716,
        717,
        718,
        719,
        720,
        721,
        722,
        723,
        724,
        725,
        726,
        727,
        728,
        729,
        730,
        731,
        732,
        733,
        734,
        735,
        736,
        737,
        738,
        739,
        740,
        741,
        742,
        743,
        744,
        745,
    };

    public static readonly int[] IconIds =
    {
        0x945,
        0x946,
        0x947,
        0x948,
        0x949,
        0x94A,
        0x9B8B,
        0x9B8C,
        0x9B8D,
        0x9B8E,
        0x9B8F,
        0x9B90,
        0x9B91,
        0x9B92,
        0x9B93,
        0x9B94,
        0x9B95,
        0x9B96,
        0x9B97,
        0x9B98,
        0x9B99,
        0x9B9A,
        0x9B9B,
        0x9B9C,
        0x9B9D,
        0x9B9E,
        0x9B9F,
        0x9BA0,
        0x9BA1,
        0x9BA2,
        0x9BA3,
        0x9BA4,
        0x9BA5,
        0x9BA6,
        0x9BA7,
        0x9BA8,
        0x9BA9,
        0x9BAA,
        0x9BAB,
        0x9BAC,
        0x9BAD,
        0x9BAE,
        0x9BAF,
        0x9BB0,
        0x9BB1,
    };

    public static readonly string[] PowerWords =
    {
        "Uus Por",
        "An Zu",
        "Kal Mani Tym",
        "Uus Jux Sanct",
        "In Jux Hur Rel",
        "Kal Des Mani Tym",
        "In Grav Corp",
        "Uus Ort Grav",
        "In Vas Xen Por",
        "Vas Ylem Wis",
        "In Corp Xen Por",
        "Uus Corp Grav",
        "Faerkulggen",
        "Lartarisstree",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
    };

    public static readonly int[] ManaCost =
    {
        16,
        22,
        16,
        18,
        24,
        26,
        50,
        0,
        40,
        40,
        40,
        40,
        40,
        50,
        0,
        10,
        40,
        0,
        10,
        50,
        10,
        10,
        30,
        25,
        30,
        20,
        20,
        20,
        20,
        20,
        20,
        40,
        50,
        50,
        40,
        10,
        20,
        30,
        0,
        20,
        20,
        0,
        40,
        40,
        0,
    };

    public static readonly int[] MinSkill =
    {
        90,
        90,
        90,
        90,
        90,
        90,
        90,
        90,
        90,
        90,
        90,
        90,
        90,
        90,
        90,
        90,
        90,
        90,
        90,
        90,
        90,
        90,
        90,
        90,
        90,
        90,
        90,
        90,
        90,
        90,
        90,
        90,
        90,
        90,
        90,
        90,
        90,
        90,
        90,
        90,
        90,
        90,
        90,
        90,
        90,
    };

    public static readonly int[] TithingCost =
    {
        4,
        5,
        4,
        5,
        10,
        12,
        35,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        35,
        35,
        4,
        0,
        0,
        0,
        20,
        0,
        0,
        20,
        0,
        20,
        0,
        0,
        0,
        0,
        0,
        10,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    };

    public static readonly string[] Reagents =
    {
        "",
        "",
        "",
        "",
        "",
        "",
        "Black Pearl, Blood Moss, Spider's Silk",
        "Blood Moss, Ginseng, Mandrake Root",
        "Dragons Blood, Demon Bone",
        "Fertile Dirt, Bone",
        "Daemon Blood, Pig Iron, Bat Wing",
        "Nox Crystal, Bat Wing, Grave Dust",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
    };
}
