//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassicUO.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClassicUO.Resources.ResErrorMessages", typeof(ResErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another character from this account is currently online in this world.  You must either log in as that character or wait for it to time out..
        /// </summary>
        public static string AnotherCharacterOnline {
            get {
                return ResourceManager.GetString("AnotherCharacterOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This character already exists.
        ///Playing....
        /// </summary>
        public static string CharacterAlreadyExists {
            get {
                return ResourceManager.GetString("CharacterAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This character does not exist anymore.  You will have to recreate it..
        /// </summary>
        public static string CharacterDoesNotExist {
            get {
                return ResourceManager.GetString("CharacterDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That character is not old enough to delete. The character must be 7 days old before it can be deleted..
        /// </summary>
        public static string CharacterIsNotOldEnough {
            get {
                return ResourceManager.GetString("CharacterIsNotOldEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That character is currently queued for backup and cannot be deleted..
        /// </summary>
        public static string CharacterIsQueuedForBackup {
            get {
                return ResourceManager.GetString("CharacterIsQueuedForBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That character password is invalid..
        /// </summary>
        public static string CharacterPasswordInvalid {
            get {
                return ResourceManager.GetString("CharacterPasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character transfer in progress..
        /// </summary>
        public static string CharacterTransferInProgress {
            get {
                return ResourceManager.GetString("CharacterTransferInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client could not attach to the game server. It must have been taken down, please wait a few minutes and try again..
        /// </summary>
        public static string ClientCouldNotAttachToServer {
            get {
                return ResourceManager.GetString("ClientCouldNotAttachToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid UO directory.
        /// </summary>
        public static string ClientPathIsNotAValidUODirectory {
            get {
                return ResourceManager.GetString("ClientPathIsNotAValidUODirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication problem..
        /// </summary>
        public static string CommunicationProblem {
            get {
                return ResourceManager.GetString("CommunicationProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not attach to game server..
        /// </summary>
        public static string CouldNotAttachServer {
            get {
                return ResourceManager.GetString("CouldNotAttachServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t carry out your request..
        /// </summary>
        public static string CouldntCarryOutYourRequest {
            get {
                return ResourceManager.GetString("CouldntCarryOutYourRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t connect to Ultima Online.  Please try again in a few moments..
        /// </summary>
        public static string CouldntConnectToUO {
            get {
                return ResourceManager.GetString("CouldntConnectToUO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred in the synchronization between the login servers and this world.  Please close your client and try again..
        /// </summary>
        public static string ErrorInSynchronization {
            get {
                return ResourceManager.GetString("ErrorInSynchronization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General IGR authentication failure..
        /// </summary>
        public static string GeneralIGRAuthenticationFailure {
            get {
                return ResourceManager.GetString("GeneralIGRAuthenticationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been idle for too long.  If you do not do anything in the next minute, you will be logged out..
        /// </summary>
        public static string IdleTooLong {
            get {
                return ResourceManager.GetString("IdleTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect name/password..
        /// </summary>
        public static string IncorrectNamePassword {
            get {
                return ResourceManager.GetString("IncorrectNamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password.
        /// </summary>
        public static string IncorrectPassword {
            get {
                return ResourceManager.GetString("IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Someone is already using this account..
        /// </summary>
        public static string SomeoneIsAlreadyUsingThisAccount {
            get {
                return ResourceManager.GetString("SomeoneIsAlreadyUsingThisAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That character does not exist..
        /// </summary>
        public static string ThatCharacterDoesNotExist {
            get {
                return ResourceManager.GetString("ThatCharacterDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That character is being played right now..
        /// </summary>
        public static string ThatCharacterIsBeingPlayed {
            get {
                return ResourceManager.GetString("ThatCharacterIsBeingPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That is out of sight..
        /// </summary>
        public static string ThatIsOutOfSight {
            get {
                return ResourceManager.GetString("ThatIsOutOfSight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That is too far away..
        /// </summary>
        public static string ThatIsTooFarAway {
            get {
                return ResourceManager.GetString("ThatIsTooFarAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That item does not belong to you.  You&apos;ll have to steal it..
        /// </summary>
        public static string ThatItemDoesNotBelongToYou {
            get {
                return ResourceManager.GetString("ThatItemDoesNotBelongToYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IGR concurrency limit has been met..
        /// </summary>
        public static string TheIGRConcurrencyLimitHasBeenMet {
            get {
                return ResourceManager.GetString("TheIGRConcurrencyLimitHasBeenMet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IGR time limit has been met..
        /// </summary>
        public static string TheIGRTimeLimitHasBeenMet {
            get {
                return ResourceManager.GetString("TheIGRTimeLimitHasBeenMet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already holding an item..
        /// </summary>
        public static string YouAreAlreadyHoldingAnItem {
            get {
                return ResourceManager.GetString("YouAreAlreadyHoldingAnItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not pick that up..
        /// </summary>
        public static string YouCanNotPickThatUp {
            get {
                return ResourceManager.GetString("YouCanNotPickThatUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account credentials are invalid..
        /// </summary>
        public static string YourAccountCredentialsAreInvalid {
            get {
                return ResourceManager.GetString("YourAccountCredentialsAreInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been blocked..
        /// </summary>
        public static string YourAccountHasBeenBlocked {
            get {
                return ResourceManager.GetString("YourAccountHasBeenBlocked", resourceCulture);
            }
        }
    }
}
