//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassicUO.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResGeneral {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResGeneral() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClassicUO.Resources.ResGeneral", typeof(ResGeneral).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %1, a conference moderator, has kicked you out of the conference..
        /// </summary>
        public static string AConferenceModeratorKickedYou {
            get {
                return ResourceManager.GetString("AConferenceModeratorKickedYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fierce storm approaches..
        /// </summary>
        public static string AFierceStormApproaches {
            get {
                return ResourceManager.GetString("AFierceStormApproaches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Alliance][{0}].
        /// </summary>
        public static string Alliance0 {
            get {
                return ResourceManager.GetString("Alliance0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always run is now off..
        /// </summary>
        public static string AlwaysRunIsNowOff {
            get {
                return ResourceManager.GetString("AlwaysRunIsNowOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always run is now on..
        /// </summary>
        public static string AlwaysRunIsNowOn {
            get {
                return ResourceManager.GetString("AlwaysRunIsNowOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A storm is brewing..
        /// </summary>
        public static string AStormIsBrewing {
            get {
                return ResourceManager.GetString("AStormIsBrewing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backpack.
        /// </summary>
        public static string Backpack {
            get {
                return ResourceManager.GetString("Backpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %1, a conference moderator, has banned you from the conference..
        /// </summary>
        public static string BannedYouFromTheConference {
            get {
                return ResourceManager.GetString("BannedYouFromTheConference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bard.
        /// </summary>
        public static string Bard {
            get {
                return ResourceManager.GetString("Bard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bat Wing.
        /// </summary>
        public static string BatWing {
            get {
                return ResourceManager.GetString("BatWing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black Pearl.
        /// </summary>
        public static string BlackPearl {
            get {
                return ResourceManager.GetString("BlackPearl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloodmoss.
        /// </summary>
        public static string Bloodmoss {
            get {
                return ResourceManager.GetString("Bloodmoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bow.
        /// </summary>
        public static string Bow {
            get {
                return ResourceManager.GetString("Bow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete this group..
        /// </summary>
        public static string CannotDeleteThisGroup {
            get {
                return ResourceManager.GetString("CannotDeleteThisGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your internet connection and try again.
        /// </summary>
        public static string CheckYourConnectionAndTryAgain {
            get {
                return ResourceManager.GetString("CheckYourConnectionAndTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://classicuo.eu.
        /// </summary>
        public static string ClassicUOLink {
            get {
                return ResourceManager.GetString("ClassicUOLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientViewRange is now {0}..
        /// </summary>
        public static string ClientViewRangeIsNow0 {
            get {
                return ResourceManager.GetString("ClientViewRangeIsNow0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combat.
        /// </summary>
        public static string Combat {
            get {
                return ResourceManager.GetString("Combat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conference %1 renamed to %2..
        /// </summary>
        public static string Conference1RenamedTo2 {
            get {
                return ResourceManager.GetString("Conference1RenamedTo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        public static string Connecting {
            get {
                return ResourceManager.GetString("Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection lost:
        ///{0}.
        /// </summary>
        public static string ConnectionLost0 {
            get {
                return ResourceManager.GetString("ConnectionLost0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crafted by .
        /// </summary>
        public static string CraftedBy {
            get {
                return ResourceManager.GetString("CraftedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating character....
        /// </summary>
        public static string CreatingCharacter {
            get {
                return ResourceManager.GetString("CreatingCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current DateTime.Now is {0}.
        /// </summary>
        public static string CurrentDateTimeNowIs0 {
            get {
                return ResourceManager.GetString("CurrentDateTimeNowIs0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czech.
        /// </summary>
        public static string Czech {
            get {
                return ResourceManager.GetString("Czech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daemon Blood.
        /// </summary>
        public static string DaemonBlood {
            get {
                return ResourceManager.GetString("DaemonBlood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to decreased.
        /// </summary>
        public static string Decreased {
            get {
                return ResourceManager.GetString("Decreased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current profile has been set as the default for new characters..
        /// </summary>
        public static string DefaultProfileSet {
            get {
                return ResourceManager.GetString("DefaultProfileSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dexterity.
        /// </summary>
        public static string Dexterity {
            get {
                return ResourceManager.GetString("Dexterity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        public static string EmoteChar {
            get {
                return ResourceManager.GetString("EmoteChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entering Britannia....
        /// </summary>
        public static string EnteringBritannia {
            get {
                return ResourceManager.GetString("EnteringBritannia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity not found..
        /// </summary>
        public static string EntityNotFound {
            get {
                return ResourceManager.GetString("EntityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From now on, everyone in the conference will have speaking privileges by default..
        /// </summary>
        public static string EveryoneWillHaveSpeakingPrivs {
            get {
                return ResourceManager.GetString("EveryoneWillHaveSpeakingPrivs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garlic.
        /// </summary>
        public static string Garlic {
            get {
                return ResourceManager.GetString("Garlic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ginseng.
        /// </summary>
        public static string Ginseng {
            get {
                return ResourceManager.GetString("Ginseng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grab Bag not found, setting to Backpack..
        /// </summary>
        public static string GrabBagNotFound {
            get {
                return ResourceManager.GetString("GrabBagNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grab Bag set: {0}.
        /// </summary>
        public static string GrabBagSet0 {
            get {
                return ResourceManager.GetString("GrabBagSet0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %1, a conference moderator, has granted you speaking privileges in this conference..
        /// </summary>
        public static string GrantedYouSpeakingPrivileges {
            get {
                return ResourceManager.GetString("GrantedYouSpeakingPrivileges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grave Dust.
        /// </summary>
        public static string GraveDust {
            get {
                return ResourceManager.GetString("GraveDust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Guild][{0}].
        /// </summary>
        public static string Guild0 {
            get {
                return ResourceManager.GetString("Guild0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %1 has been kicked out of the conference..
        /// </summary>
        public static string HasBeenKickedOutOfTheConference {
            get {
                return ResourceManager.GetString("HasBeenKickedOutOfTheConference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %1 has chosen to ignore you. None of your messages to them will get through..
        /// </summary>
        public static string HasChosenToIgnoreYou {
            get {
                return ResourceManager.GetString("HasChosenToIgnoreYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %1 has chosen to not receive private messages at the moment..
        /// </summary>
        public static string HasChosenToNotReceivePM {
            get {
                return ResourceManager.GetString("HasChosenToNotReceivePM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %1 has made you a conference moderator..
        /// </summary>
        public static string HasMadeYouAConferenceModerator {
            get {
                return ResourceManager.GetString("HasMadeYouAConferenceModerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %1 has removed you from the list of conference moderators..
        /// </summary>
        public static string HasRemovedYouFromModerators {
            get {
                return ResourceManager.GetString("HasRemovedYouFromModerators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hits.
        /// </summary>
        public static string Hits {
            get {
                return ResourceManager.GetString("Hits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to increased.
        /// </summary>
        public static string Increased {
            get {
                return ResourceManager.GetString("Increased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to intelligence.
        /// </summary>
        public static string Intelligence {
            get {
                return ResourceManager.GetString("Intelligence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invariant.
        /// </summary>
        public static string Invariant {
            get {
                return ResourceManager.GetString("Invariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %1 is known in the lands of Britannia as %2..
        /// </summary>
        public static string IsKnownInTheLandsOfBritanniaAs2 {
            get {
                return ResourceManager.GetString("IsKnownInTheLandsOfBritanniaAs2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %1 is no longer a conference moderator..
        /// </summary>
        public static string IsNoLongerAConferenceModerator {
            get {
                return ResourceManager.GetString("IsNoLongerAConferenceModerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %1 is now a conference moderator..
        /// </summary>
        public static string IsNowAConferenceModerator {
            get {
                return ResourceManager.GetString("IsNowAConferenceModerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %1 is remaining anonymous..
        /// </summary>
        public static string IsRemainingAnonymous {
            get {
                return ResourceManager.GetString("IsRemainingAnonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It begins to rain..
        /// </summary>
        public static string ItBeginsToRain {
            get {
                return ResourceManager.GetString("ItBeginsToRain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It begins to snow..
        /// </summary>
        public static string ItBeginsToSnow {
            get {
                return ResourceManager.GetString("ItBeginsToSnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item ID: {0}
        ///Hue: {1}.
        /// </summary>
        public static string ItemID0Hue1 {
            get {
                return ResourceManager.GetString("ItemID0Hue1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal.
        /// </summary>
        public static string Journal {
            get {
                return ResourceManager.GetString("Journal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging into Shard.
        /// </summary>
        public static string LoggingIntoShard {
            get {
                return ResourceManager.GetString("LoggingIntoShard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magic.
        /// </summary>
        public static string Magic {
            get {
                return ResourceManager.GetString("Magic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mana.
        /// </summary>
        public static string Mana {
            get {
                return ResourceManager.GetString("Mana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandrake Root.
        /// </summary>
        public static string MandrakeRoot {
            get {
                return ResourceManager.GetString("MandrakeRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous.
        /// </summary>
        public static string Miscellaneous {
            get {
                return ResourceManager.GetString("Miscellaneous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From now on, only moderators will have speaking privileges in this conference by default..
        /// </summary>
        public static string ModeratorsWillHaveSpeakingPrivs {
            get {
                return ResourceManager.GetString("ModeratorsWillHaveSpeakingPrivs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: {0} - {1:F1}.
        /// </summary>
        public static string Name0Val1 {
            get {
                return ResourceManager.GetString("Name0Val1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nightshade.
        /// </summary>
        public static string Nightshade {
            get {
                return ResourceManager.GetString("Nightshade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %1 no longer has speaking privileges in this conference..
        /// </summary>
        public static string NoLongerHasSpeakingPrivileges {
            get {
                return ResourceManager.GetString("NoLongerHasSpeakingPrivileges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No name.
        /// </summary>
        public static string NoName {
            get {
                return ResourceManager.GetString("NoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The moderator of this conference has not given you speaking privileges..
        /// </summary>
        public static string NotGivenYouSpeakingPrivileges {
            get {
                return ResourceManager.GetString("NotGivenYouSpeakingPrivileges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;not seeing&gt;.
        /// </summary>
        public static string NotSeeing {
            get {
                return ResourceManager.GetString("NotSeeing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now following..
        /// </summary>
        public static string NowFollowing {
            get {
                return ResourceManager.GetString("NowFollowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %1 now has speaking privileges in this conference..
        /// </summary>
        public static string NowHasSpeakingPrivileges {
            get {
                return ResourceManager.GetString("NowHasSpeakingPrivileges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nox Crystal.
        /// </summary>
        public static string NoxCrystal {
            get {
                return ResourceManager.GetString("NoxCrystal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouch!.
        /// </summary>
        public static string Ouch {
            get {
                return ResourceManager.GetString("Ouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paperdoll.
        /// </summary>
        public static string Paperdoll {
            get {
                return ResourceManager.GetString("Paperdoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Party][{0}].
        /// </summary>
        public static string Party0 {
            get {
                return ResourceManager.GetString("Party0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password to the conference has been changed..
        /// </summary>
        public static string PasswordToTheConferenceChanged {
            get {
                return ResourceManager.GetString("PasswordToTheConferenceChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pathfinding!.
        /// </summary>
        public static string Pathfinding {
            get {
                return ResourceManager.GetString("Pathfinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pig Iron.
        /// </summary>
        public static string PigIron {
            get {
                return ResourceManager.GetString("PigIron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit
        ///Ultima Online?.
        /// </summary>
        public static string QuitPrompt {
            get {
                return ResourceManager.GetString("QuitPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radar.
        /// </summary>
        public static string Radar {
            get {
                return ResourceManager.GetString("Radar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnect, please wait...`{0}`
        ///`{1}`.
        /// </summary>
        public static string ReconnectPleaseWait01 {
            get {
                return ResourceManager.GetString("ReconnectPleaseWait01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %1, a conference moderator, has removed your speaking privileges for this conference..
        /// </summary>
        public static string RemovedYourSpeakingPrivileges {
            get {
                return ResourceManager.GetString("RemovedYourSpeakingPrivileges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salute.
        /// </summary>
        public static string Salute {
            get {
                return ResourceManager.GetString("Salute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot stored in: {0}.
        /// </summary>
        public static string ScreenshotStoredIn0 {
            get {
                return ResourceManager.GetString("ScreenshotStoredIn0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spiders Silk.
        /// </summary>
        public static string SpidersSilk {
            get {
                return ResourceManager.GetString("SpidersSilk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stam.
        /// </summary>
        public static string Stam {
            get {
                return ResourceManager.GetString("Stam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped following..
        /// </summary>
        public static string StoppedFollowing {
            get {
                return ResourceManager.GetString("StoppedFollowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to strength.
        /// </summary>
        public static string Strength {
            get {
                return ResourceManager.GetString("Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sulfurous Ash.
        /// </summary>
        public static string SulfurousAsh {
            get {
                return ResourceManager.GetString("SulfurousAsh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target: {0}.
        /// </summary>
        public static string Target0 {
            get {
                return ResourceManager.GetString("Target0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target an Item to grab it..
        /// </summary>
        public static string TargetAnItemToGrabIt {
            get {
                return ResourceManager.GetString("TargetAnItemToGrabIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [WARN] - TargetSystem On/Off not implemented.
        /// </summary>
        public static string TargetSystemNotImplemented {
            get {
                return ResourceManager.GetString("TargetSystemNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That is not a valid conference name..
        /// </summary>
        public static string ThatIsNotAValidConferenceName {
            get {
                return ResourceManager.GetString("ThatIsNotAValidConferenceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That is not the correct password..
        /// </summary>
        public static string ThatIsNotTheCorrectPassword {
            get {
                return ResourceManager.GetString("ThatIsNotTheCorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry--the conference named &apos;%1&apos; is full and no more players are allowed in..
        /// </summary>
        public static string TheConferenceNamed1IsFull {
            get {
                return ResourceManager.GetString("TheConferenceNamed1IsFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a conference of that name..
        /// </summary>
        public static string ThereIsAlreadyAConference {
            get {
                return ResourceManager.GetString("ThereIsAlreadyAConference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no conference named &apos;%1&apos;..
        /// </summary>
        public static string ThereIsNoConferenceNamed1 {
            get {
                return ResourceManager.GetString("ThereIsNoConferenceNamed1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no player named &apos;%1&apos;..
        /// </summary>
        public static string ThereIsNoPlayerNamed1 {
            get {
                return ResourceManager.GetString("ThereIsNoPlayerNamed1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thieving.
        /// </summary>
        public static string Thieving {
            get {
                return ResourceManager.GetString("Thieving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This may flag
        ///you criminal!.
        /// </summary>
        public static string ThisMayFlagYouCriminal {
            get {
                return ResourceManager.GetString("ThisMayFlagYouCriminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade Skills.
        /// </summary>
        public static string TradeSkills {
            get {
                return ResourceManager.GetString("TradeSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying Account....
        /// </summary>
        public static string VerifyingAccount {
            get {
                return ResourceManager.GetString("VerifyingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wilderness.
        /// </summary>
        public static string Wilderness {
            get {
                return ResourceManager.GetString("Wilderness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClassicUO - {0}.
        /// </summary>
        public static string WindowTitle0 {
            get {
                return ResourceManager.GetString("WindowTitle0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already ignoring %1..
        /// </summary>
        public static string YouAreAlreadyIgnoring1 {
            get {
                return ResourceManager.GetString("YouAreAlreadyIgnoring1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already ignoring the maximum number of people..
        /// </summary>
        public static string YouAreAlreadyIgnoringMaximum {
            get {
                return ResourceManager.GetString("YouAreAlreadyIgnoringMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already in the conference &apos;%1&apos;..
        /// </summary>
        public static string YouAreAlreadyInTheConference1 {
            get {
                return ResourceManager.GetString("YouAreAlreadyInTheConference1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are banning %1 from this conference..
        /// </summary>
        public static string YouAreBanning1FromThisConference {
            get {
                return ResourceManager.GetString("YouAreBanning1FromThisConference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are dead..
        /// </summary>
        public static string YouAreDead {
            get {
                return ResourceManager.GetString("YouAreDead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are no longer ignoring %1..
        /// </summary>
        public static string YouAreNoLongerIgnoring1 {
            get {
                return ResourceManager.GetString("YouAreNoLongerIgnoring1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are no longer ignoring anyone..
        /// </summary>
        public static string YouAreNoLongerIgnoringAnyone {
            get {
                return ResourceManager.GetString("YouAreNoLongerIgnoringAnyone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not ignoring %1..
        /// </summary>
        public static string YouAreNotIgnoring1 {
            get {
                return ResourceManager.GetString("YouAreNotIgnoring1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are no longer showing your character name to any players who inquire with the whois command..
        /// </summary>
        public static string YouAreNotShowingYourCharName {
            get {
                return ResourceManager.GetString("YouAreNotShowingYourCharName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are now ignoring %1..
        /// </summary>
        public static string YouAreNowIgnoring1 {
            get {
                return ResourceManager.GetString("YouAreNowIgnoring1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are now showing your character name to any players who inquire with the whois command..
        /// </summary>
        public static string YouAreShowingYourCharName {
            get {
                return ResourceManager.GetString("YouAreShowingYourCharName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can now receive private messages..
        /// </summary>
        public static string YouCanNowReceivePM {
            get {
                return ResourceManager.GetString("YouCanNowReceivePM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been banned from this conference..
        /// </summary>
        public static string YouHaveBeenBanned {
            get {
                return ResourceManager.GetString("YouHaveBeenBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have joined the &apos;{0}&apos; channel..
        /// </summary>
        public static string YouHaveJoinedThe0Channel {
            get {
                return ResourceManager.GetString("YouHaveJoinedThe0Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have left the &apos;{0}&apos; channel..
        /// </summary>
        public static string YouHaveLeftThe0Channel {
            get {
                return ResourceManager.GetString("YouHaveLeftThe0Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be in a conference to do this. To join a conference, select one from the Conference menu..
        /// </summary>
        public static string YouMustBeInAConference {
            get {
                return ResourceManager.GetString("YouMustBeInAConference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must have operator status to do this..
        /// </summary>
        public static string YouMustHaveOperatorStatus {
            get {
                return ResourceManager.GetString("YouMustHaveOperatorStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your {0} has changed by {1}.  It is now {2}.
        /// </summary>
        public static string Your0HasChangedBy1ItIsNow2 {
            get {
                return ResourceManager.GetString("Your0HasChangedBy1ItIsNow2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your skill in {0} has {1} by {2:F1}.  It is now {3:F1}..
        /// </summary>
        public static string YourSkillIn0Has1By2ItIsNow3 {
            get {
                return ResourceManager.GetString("YourSkillIn0Has1By2ItIsNow3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Ultima Online client version seems to be invalid.
        ///Download the official Launcher to setup and run your game.
        ///
        ///Link: classicuo.eu.
        /// </summary>
        public static string YourUOClientVersionIsInvalid {
            get {
                return ResourceManager.GetString("YourUOClientVersionIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Ultima Online directory seems to be invalid.
        ///Download the official Launcher to setup and run your game.
        ///
        ///Link: classicuo.eu.
        /// </summary>
        public static string YourUODirectoryIsInvalid {
            get {
                return ResourceManager.GetString("YourUODirectoryIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You see.
        /// </summary>
        public static string YouSee {
            get {
                return ResourceManager.GetString("YouSee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will no longer receive private messages. Those who send you a message will be notified that you are blocking incoming messages..
        /// </summary>
        public static string YouWillNoLongerReceivePM {
            get {
                return ResourceManager.GetString("YouWillNoLongerReceivePM", resourceCulture);
            }
        }
    }
}
