//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassicUO.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResGumps {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResGumps() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ClassicUO.Resources.ResGumps", typeof(ResGumps).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string CombatSpells {
            get {
                return ResourceManager.GetString("CombatSpells", resourceCulture);
            }
        }
        
        public static string Containers {
            get {
                return ResourceManager.GetString("Containers", resourceCulture);
            }
        }
        
        public static string Counters {
            get {
                return ResourceManager.GetString("Counters", resourceCulture);
            }
        }
        
        public static string Experimental {
            get {
                return ResourceManager.GetString("Experimental", resourceCulture);
            }
        }
        
        public static string Fonts {
            get {
                return ResourceManager.GetString("Fonts", resourceCulture);
            }
        }
        
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        public static string InfoBar {
            get {
                return ResourceManager.GetString("InfoBar", resourceCulture);
            }
        }
        
        public static string Macros {
            get {
                return ResourceManager.GetString("Macros", resourceCulture);
            }
        }
        
        public static string Sound {
            get {
                return ResourceManager.GetString("Sound", resourceCulture);
            }
        }
        
        public static string Speech {
            get {
                return ResourceManager.GetString("Speech", resourceCulture);
            }
        }
        
        public static string Tooltip {
            get {
                return ResourceManager.GetString("Tooltip", resourceCulture);
            }
        }
        
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        public static string AltCloseGumps {
            get {
                return ResourceManager.GetString("AltCloseGumps", resourceCulture);
            }
        }
        
        public static string AltMoveGumps {
            get {
                return ResourceManager.GetString("AltMoveGumps", resourceCulture);
            }
        }
        
        public static string AlwaysRun {
            get {
                return ResourceManager.GetString("AlwaysRun", resourceCulture);
            }
        }
        
        public static string AlwaysRunHidden {
            get {
                return ResourceManager.GetString("AlwaysRunHidden", resourceCulture);
            }
        }
        
        public static string AutoOpenCorpses {
            get {
                return ResourceManager.GetString("AutoOpenCorpses", resourceCulture);
            }
        }
        
        public static string AutoOpenDoors {
            get {
                return ResourceManager.GetString("AutoOpenDoors", resourceCulture);
            }
        }
        
        public static string CircleTransType_Full {
            get {
                return ResourceManager.GetString("CircleTransType_Full", resourceCulture);
            }
        }
        
        public static string CircleTransType_Gradient {
            get {
                return ResourceManager.GetString("CircleTransType_Gradient", resourceCulture);
            }
        }
        
        public static string ClickCloseAllGumps {
            get {
                return ResourceManager.GetString("ClickCloseAllGumps", resourceCulture);
            }
        }
        
        public static string CorpseOpt_Both {
            get {
                return ResourceManager.GetString("CorpseOpt_Both", resourceCulture);
            }
        }
        
        public static string CorpseOpt_None {
            get {
                return ResourceManager.GetString("CorpseOpt_None", resourceCulture);
            }
        }
        
        public static string CorpseOpt_NotHid {
            get {
                return ResourceManager.GetString("CorpseOpt_NotHid", resourceCulture);
            }
        }
        
        public static string CorpseOpt_NotTar {
            get {
                return ResourceManager.GetString("CorpseOpt_NotTar", resourceCulture);
            }
        }
        
        public static string DisableMenu {
            get {
                return ResourceManager.GetString("DisableMenu", resourceCulture);
            }
        }
        
        public static string DragHumanoidsOnly {
            get {
                return ResourceManager.GetString("DragHumanoidsOnly", resourceCulture);
            }
        }
        
        public static string EnableCircleTrans {
            get {
                return ResourceManager.GetString("EnableCircleTrans", resourceCulture);
            }
        }
        
        public static string EnableDragHPBars {
            get {
                return ResourceManager.GetString("EnableDragHPBars", resourceCulture);
            }
        }
        
        public static string EnablePathfinding {
            get {
                return ResourceManager.GetString("EnablePathfinding", resourceCulture);
            }
        }
        
        public static string FPSInactive {
            get {
                return ResourceManager.GetString("FPSInactive", resourceCulture);
            }
        }
        
        public static string GridLoot_Both {
            get {
                return ResourceManager.GetString("GridLoot_Both", resourceCulture);
            }
        }
        
        public static string GridLoot_GridOnly {
            get {
                return ResourceManager.GetString("GridLoot_GridOnly", resourceCulture);
            }
        }
        
        public static string GridLoot_None {
            get {
                return ResourceManager.GetString("GridLoot_None", resourceCulture);
            }
        }
        
        public static string HideRoofTiles {
            get {
                return ResourceManager.GetString("HideRoofTiles", resourceCulture);
            }
        }
        
        public static string HideVegetation {
            get {
                return ResourceManager.GetString("HideVegetation", resourceCulture);
            }
        }
        
        public static string HighlighState {
            get {
                return ResourceManager.GetString("HighlighState", resourceCulture);
            }
        }
        
        public static string HighlightObjects {
            get {
                return ResourceManager.GetString("HighlightObjects", resourceCulture);
            }
        }
        
        public static string HPFields_Normal {
            get {
                return ResourceManager.GetString("HPFields_Normal", resourceCulture);
            }
        }
        
        public static string HPFields_Static {
            get {
                return ResourceManager.GetString("HPFields_Static", resourceCulture);
            }
        }
        
        public static string HPFields_Tile {
            get {
                return ResourceManager.GetString("HPFields_Tile", resourceCulture);
            }
        }
        
        public static string HPShow_Always {
            get {
                return ResourceManager.GetString("HPShow_Always", resourceCulture);
            }
        }
        
        public static string HPShow_Less {
            get {
                return ResourceManager.GetString("HPShow_Less", resourceCulture);
            }
        }
        
        public static string HPShow_Smart {
            get {
                return ResourceManager.GetString("HPShow_Smart", resourceCulture);
            }
        }
        
        public static string HPType_MobileDead {
            get {
                return ResourceManager.GetString("HPType_MobileDead", resourceCulture);
            }
        }
        
        public static string HPType_MobileOOR {
            get {
                return ResourceManager.GetString("HPType_MobileOOR", resourceCulture);
            }
        }
        
        public static string HPType_None {
            get {
                return ResourceManager.GetString("HPType_None", resourceCulture);
            }
        }
        
        public static string HP_Both {
            get {
                return ResourceManager.GetString("HP_Both", resourceCulture);
            }
        }
        
        public static string HP_Line {
            get {
                return ResourceManager.GetString("HP_Line", resourceCulture);
            }
        }
        
        public static string HP_Percentage {
            get {
                return ResourceManager.GetString("HP_Percentage", resourceCulture);
            }
        }
        
        public static string InvulColor {
            get {
                return ResourceManager.GetString("InvulColor", resourceCulture);
            }
        }
        
        public static string KeyMod_Ctrl {
            get {
                return ResourceManager.GetString("KeyMod_Ctrl", resourceCulture);
            }
        }
        
        public static string KeyMod_None {
            get {
                return ResourceManager.GetString("KeyMod_None", resourceCulture);
            }
        }
        
        public static string KeyMod_Shift {
            get {
                return ResourceManager.GetString("KeyMod_Shift", resourceCulture);
            }
        }
        
        public static string MarkCaveTiles {
            get {
                return ResourceManager.GetString("MarkCaveTiles", resourceCulture);
            }
        }
        
        public static string ObjAlphaFading {
            get {
                return ResourceManager.GetString("ObjAlphaFading", resourceCulture);
            }
        }
        
        public static string OutOfRangeColor {
            get {
                return ResourceManager.GetString("OutOfRangeColor", resourceCulture);
            }
        }
        
        public static string ParalyzedColor {
            get {
                return ResourceManager.GetString("ParalyzedColor", resourceCulture);
            }
        }
        
        public static string PoisonedColor {
            get {
                return ResourceManager.GetString("PoisonedColor", resourceCulture);
            }
        }
        
        public static string SallosEasyGrab {
            get {
                return ResourceManager.GetString("SallosEasyGrab", resourceCulture);
            }
        }
        
        public static string SaveHPBarsOnLogout {
            get {
                return ResourceManager.GetString("SaveHPBarsOnLogout", resourceCulture);
            }
        }
        
        public static string ShiftContext {
            get {
                return ResourceManager.GetString("ShiftContext", resourceCulture);
            }
        }
        
        public static string ShiftPathfinding {
            get {
                return ResourceManager.GetString("ShiftPathfinding", resourceCulture);
            }
        }
        
        public static string ShiftStack {
            get {
                return ResourceManager.GetString("ShiftStack", resourceCulture);
            }
        }
        
        public static string ShowGumpPartyInv {
            get {
                return ResourceManager.GetString("ShowGumpPartyInv", resourceCulture);
            }
        }
        
        public static string ShowHousesContent {
            get {
                return ResourceManager.GetString("ShowHousesContent", resourceCulture);
            }
        }
        
        public static string ShowHP {
            get {
                return ResourceManager.GetString("ShowHP", resourceCulture);
            }
        }
        
        public static string ShowIncCorpses {
            get {
                return ResourceManager.GetString("ShowIncCorpses", resourceCulture);
            }
        }
        
        public static string ShowIncMobiles {
            get {
                return ResourceManager.GetString("ShowIncMobiles", resourceCulture);
            }
        }
        
        public static string ShowTarRangeIndic {
            get {
                return ResourceManager.GetString("ShowTarRangeIndic", resourceCulture);
            }
        }
        
        public static string SkipEmptyCorpses {
            get {
                return ResourceManager.GetString("SkipEmptyCorpses", resourceCulture);
            }
        }
        
        public static string SmoothBoat {
            get {
                return ResourceManager.GetString("SmoothBoat", resourceCulture);
            }
        }
        
        public static string SmoothDoors {
            get {
                return ResourceManager.GetString("SmoothDoors", resourceCulture);
            }
        }
        
        public static string StandardSkillGump {
            get {
                return ResourceManager.GetString("StandardSkillGump", resourceCulture);
            }
        }
        
        public static string TabCombat {
            get {
                return ResourceManager.GetString("TabCombat", resourceCulture);
            }
        }
        
        public static string TextAlphaFading {
            get {
                return ResourceManager.GetString("TextAlphaFading", resourceCulture);
            }
        }
        
        public static string TreesStumps {
            get {
                return ResourceManager.GetString("TreesStumps", resourceCulture);
            }
        }
        
        public static string UseBlackBackgr {
            get {
                return ResourceManager.GetString("UseBlackBackgr", resourceCulture);
            }
        }
        
        public static string UseCustomHPBars {
            get {
                return ResourceManager.GetString("UseCustomHPBars", resourceCulture);
            }
        }
        
        public static string CircleTransType {
            get {
                return ResourceManager.GetString("CircleTransType", resourceCulture);
            }
        }
        
        public static string CloseHPGumpWhen {
            get {
                return ResourceManager.GetString("CloseHPGumpWhen", resourceCulture);
            }
        }
        
        public static string CorpseOpenOptions {
            get {
                return ResourceManager.GetString("CorpseOpenOptions", resourceCulture);
            }
        }
        
        public static string CorpseOpenRange {
            get {
                return ResourceManager.GetString("CorpseOpenRange", resourceCulture);
            }
        }
        
        public static string DragKey {
            get {
                return ResourceManager.GetString("DragKey", resourceCulture);
            }
        }
        
        public static string FPS {
            get {
                return ResourceManager.GetString("FPS", resourceCulture);
            }
        }
        
        public static string GridLoot {
            get {
                return ResourceManager.GetString("GridLoot", resourceCulture);
            }
        }
        
        public static string HPFields {
            get {
                return ResourceManager.GetString("HPFields", resourceCulture);
            }
        }
        
        public static string HP_Mode {
            get {
                return ResourceManager.GetString("HP_Mode", resourceCulture);
            }
        }
        
        public static string ShopGumpSize {
            get {
                return ResourceManager.GetString("ShopGumpSize", resourceCulture);
            }
        }
        
        public static string Sounds {
            get {
                return ResourceManager.GetString("Sounds", resourceCulture);
            }
        }
        
        public static string Music {
            get {
                return ResourceManager.GetString("Music", resourceCulture);
            }
        }
        
        public static string LoginMusic {
            get {
                return ResourceManager.GetString("LoginMusic", resourceCulture);
            }
        }
        
        public static string PlayFootsteps {
            get {
                return ResourceManager.GetString("PlayFootsteps", resourceCulture);
            }
        }
        
        public static string CombatMusic {
            get {
                return ResourceManager.GetString("CombatMusic", resourceCulture);
            }
        }
        
        public static string ReproduceSoundsAndMusic {
            get {
                return ResourceManager.GetString("ReproduceSoundsAndMusic", resourceCulture);
            }
        }
        
        public static string BorderlessWindow {
            get {
                return ResourceManager.GetString("BorderlessWindow", resourceCulture);
            }
        }
        
        public static string AlwaysUseFullsizeGameWindow {
            get {
                return ResourceManager.GetString("AlwaysUseFullsizeGameWindow", resourceCulture);
            }
        }
        
        public static string LockGameWindowMovingResizing {
            get {
                return ResourceManager.GetString("LockGameWindowMovingResizing", resourceCulture);
            }
        }
        
        public static string GamePlayWindowSize {
            get {
                return ResourceManager.GetString("GamePlayWindowSize", resourceCulture);
            }
        }
        
        public static string GamePlayWindowPosition {
            get {
                return ResourceManager.GetString("GamePlayWindowPosition", resourceCulture);
            }
        }
        
        public static string DefaultZoom {
            get {
                return ResourceManager.GetString("DefaultZoom", resourceCulture);
            }
        }
        
        public static string EnableMouseWheelForZoom {
            get {
                return ResourceManager.GetString("EnableMouseWheelForZoom", resourceCulture);
            }
        }
        
        public static string ReleasingCtrlRestoresScale {
            get {
                return ResourceManager.GetString("ReleasingCtrlRestoresScale", resourceCulture);
            }
        }
        
        public static string EnableDeathScreen {
            get {
                return ResourceManager.GetString("EnableDeathScreen", resourceCulture);
            }
        }
        
        public static string BlackWhiteModeForDeadPlayer {
            get {
                return ResourceManager.GetString("BlackWhiteModeForDeadPlayer", resourceCulture);
            }
        }
        
        public static string UseOldStatusGump {
            get {
                return ResourceManager.GetString("UseOldStatusGump", resourceCulture);
            }
        }
        
        public static string Brighlight {
            get {
                return ResourceManager.GetString("Brighlight", resourceCulture);
            }
        }
        
        public static string AlternativeLights {
            get {
                return ResourceManager.GetString("AlternativeLights", resourceCulture);
            }
        }
        
        public static string SetsLightLevelToMax {
            get {
                return ResourceManager.GetString("SetsLightLevelToMax", resourceCulture);
            }
        }
        
        public static string LightLevel {
            get {
                return ResourceManager.GetString("LightLevel", resourceCulture);
            }
        }
        
        public static string DarkNights {
            get {
                return ResourceManager.GetString("DarkNights", resourceCulture);
            }
        }
        
        public static string UseColoredLights {
            get {
                return ResourceManager.GetString("UseColoredLights", resourceCulture);
            }
        }
        
        public static string Shadows {
            get {
                return ResourceManager.GetString("Shadows", resourceCulture);
            }
        }
        
        public static string AuraUnderFeet {
            get {
                return ResourceManager.GetString("AuraUnderFeet", resourceCulture);
            }
        }
        
        public static string AuraType_None {
            get {
                return ResourceManager.GetString("AuraType_None", resourceCulture);
            }
        }
        
        public static string AuraType_Warmode {
            get {
                return ResourceManager.GetString("AuraType_Warmode", resourceCulture);
            }
        }
        
        public static string AuraType_CtrlShift {
            get {
                return ResourceManager.GetString("AuraType_CtrlShift", resourceCulture);
            }
        }
        
        public static string AuraType_Always {
            get {
                return ResourceManager.GetString("AuraType_Always", resourceCulture);
            }
        }
        
        public static string CustomColorAuraForPartyMembers {
            get {
                return ResourceManager.GetString("CustomColorAuraForPartyMembers", resourceCulture);
            }
        }
        
        public static string RunMouseInASeparateThread {
            get {
                return ResourceManager.GetString("RunMouseInASeparateThread", resourceCulture);
            }
        }
        
        public static string AuraOnMouseTarget {
            get {
                return ResourceManager.GetString("AuraOnMouseTarget", resourceCulture);
            }
        }
        
        public static string AnimatedWaterEffect {
            get {
                return ResourceManager.GetString("AnimatedWaterEffect", resourceCulture);
            }
        }
        
        public static string UseXBREffectBETA {
            get {
                return ResourceManager.GetString("UseXBREffectBETA", resourceCulture);
            }
        }
        
        public static string HideChatGradient {
            get {
                return ResourceManager.GetString("HideChatGradient", resourceCulture);
            }
        }
        
        public static string NewMacro {
            get {
                return ResourceManager.GetString("NewMacro", resourceCulture);
            }
        }
        
        public static string MacroName {
            get {
                return ResourceManager.GetString("MacroName", resourceCulture);
            }
        }
        
        public static string DeleteMacro {
            get {
                return ResourceManager.GetString("DeleteMacro", resourceCulture);
            }
        }
        
        public static string MacroDeleteConfirmation {
            get {
                return ResourceManager.GetString("MacroDeleteConfirmation", resourceCulture);
            }
        }
        
        public static string UseTooltip {
            get {
                return ResourceManager.GetString("UseTooltip", resourceCulture);
            }
        }
        
        public static string DelayBeforeDisplay {
            get {
                return ResourceManager.GetString("DelayBeforeDisplay", resourceCulture);
            }
        }
        
        public static string TooltipZoom {
            get {
                return ResourceManager.GetString("TooltipZoom", resourceCulture);
            }
        }
        
        public static string TooltipBackgroundOpacity {
            get {
                return ResourceManager.GetString("TooltipBackgroundOpacity", resourceCulture);
            }
        }
        
        public static string TooltipFont {
            get {
                return ResourceManager.GetString("TooltipFont", resourceCulture);
            }
        }
        
        public static string TooltipFontHue {
            get {
                return ResourceManager.GetString("TooltipFontHue", resourceCulture);
            }
        }
        
        public static string TooltipFontSelect {
            get {
                return ResourceManager.GetString("TooltipFontSelect", resourceCulture);
            }
        }
        
        public static string OverrideGameFont {
            get {
                return ResourceManager.GetString("OverrideGameFont", resourceCulture);
            }
        }
        
        public static string ASCII {
            get {
                return ResourceManager.GetString("ASCII", resourceCulture);
            }
        }
        
        public static string Unicode {
            get {
                return ResourceManager.GetString("Unicode", resourceCulture);
            }
        }
        
        public static string ForceUnicodeInJournal {
            get {
                return ResourceManager.GetString("ForceUnicodeInJournal", resourceCulture);
            }
        }
        
        public static string SpeechFont {
            get {
                return ResourceManager.GetString("SpeechFont", resourceCulture);
            }
        }
        
        public static string ThatSClassicUO {
            get {
                return ResourceManager.GetString("ThatSClassicUO", resourceCulture);
            }
        }
        
        public static string ScaleSpeechDelay {
            get {
                return ResourceManager.GetString("ScaleSpeechDelay", resourceCulture);
            }
        }
        
        public static string SaveJournalToFileInGameFolder {
            get {
                return ResourceManager.GetString("SaveJournalToFileInGameFolder", resourceCulture);
            }
        }
        
        public static string ActiveChatWhenPressingEnter {
            get {
                return ResourceManager.GetString("ActiveChatWhenPressingEnter", resourceCulture);
            }
        }
        
        public static string UseAdditionalButtonsToActivateChat {
            get {
                return ResourceManager.GetString("UseAdditionalButtonsToActivateChat", resourceCulture);
            }
        }
        
        public static string UseShiftEnterToSendMessage {
            get {
                return ResourceManager.GetString("UseShiftEnterToSendMessage", resourceCulture);
            }
        }
        
        public static string RandomizeSpeechHues {
            get {
                return ResourceManager.GetString("RandomizeSpeechHues", resourceCulture);
            }
        }
        
        public static string SpeechColor {
            get {
                return ResourceManager.GetString("SpeechColor", resourceCulture);
            }
        }
        
        public static string EmoteColor {
            get {
                return ResourceManager.GetString("EmoteColor", resourceCulture);
            }
        }
        
        public static string YellColor {
            get {
                return ResourceManager.GetString("YellColor", resourceCulture);
            }
        }
        
        public static string WhisperColor {
            get {
                return ResourceManager.GetString("WhisperColor", resourceCulture);
            }
        }
        
        public static string PartyMessageColor {
            get {
                return ResourceManager.GetString("PartyMessageColor", resourceCulture);
            }
        }
        
        public static string GuildMessageColor {
            get {
                return ResourceManager.GetString("GuildMessageColor", resourceCulture);
            }
        }
        
        public static string AllianceMessageColor {
            get {
                return ResourceManager.GetString("AllianceMessageColor", resourceCulture);
            }
        }
        
        public static string ChatMessageColor {
            get {
                return ResourceManager.GetString("ChatMessageColor", resourceCulture);
            }
        }
        
        public static string QueryAttack {
            get {
                return ResourceManager.GetString("QueryAttack", resourceCulture);
            }
        }
        
        public static string QueryBeneficialActs_Tooltip {
            get {
                return ResourceManager.GetString("QueryBeneficialActs_Tooltip", resourceCulture);
            }
        }
        
        public static string QueryBeneficialActs {
            get {
                return ResourceManager.GetString("QueryBeneficialActs", resourceCulture);
            }
        }
        
        public static string EnableOverheadSpellFormat {
            get {
                return ResourceManager.GetString("EnableOverheadSpellFormat", resourceCulture);
            }
        }
        
        public static string EnableOverheadSpellHue {
            get {
                return ResourceManager.GetString("EnableOverheadSpellHue", resourceCulture);
            }
        }
        
        public static string UIButtonsSingleClick {
            get {
                return ResourceManager.GetString("UIButtonsSingleClick", resourceCulture);
            }
        }
        
        public static string ShowBuffDuration {
            get {
                return ResourceManager.GetString("ShowBuffDuration", resourceCulture);
            }
        }
        
        public static string InnocentColor {
            get {
                return ResourceManager.GetString("InnocentColor", resourceCulture);
            }
        }
        
        public static string FriendColor {
            get {
                return ResourceManager.GetString("FriendColor", resourceCulture);
            }
        }
        
        public static string CriminalColor {
            get {
                return ResourceManager.GetString("CriminalColor", resourceCulture);
            }
        }
        
        public static string CanAttackColor {
            get {
                return ResourceManager.GetString("CanAttackColor", resourceCulture);
            }
        }
        
        public static string MurdererColor {
            get {
                return ResourceManager.GetString("MurdererColor", resourceCulture);
            }
        }
        
        public static string EnemyColor {
            get {
                return ResourceManager.GetString("EnemyColor", resourceCulture);
            }
        }
        
        public static string BeneficSpellHue {
            get {
                return ResourceManager.GetString("BeneficSpellHue", resourceCulture);
            }
        }
        
        public static string HarmfulSpellHue {
            get {
                return ResourceManager.GetString("HarmfulSpellHue", resourceCulture);
            }
        }
        
        public static string NeutralSpellHue {
            get {
                return ResourceManager.GetString("NeutralSpellHue", resourceCulture);
            }
        }
        
        public static string SpellOverheadFormat {
            get {
                return ResourceManager.GetString("SpellOverheadFormat", resourceCulture);
            }
        }
        
        public static string EnableCounters {
            get {
                return ResourceManager.GetString("EnableCounters", resourceCulture);
            }
        }
        
        public static string HighlightOnUse {
            get {
                return ResourceManager.GetString("HighlightOnUse", resourceCulture);
            }
        }
        
        public static string EnableAbbreviatedAmountCountrs {
            get {
                return ResourceManager.GetString("EnableAbbreviatedAmountCountrs", resourceCulture);
            }
        }
        
        public static string HighlightRedWhenBelow {
            get {
                return ResourceManager.GetString("HighlightRedWhenBelow", resourceCulture);
            }
        }
        
        public static string CounterLayout {
            get {
                return ResourceManager.GetString("CounterLayout", resourceCulture);
            }
        }
        
        public static string CellSize {
            get {
                return ResourceManager.GetString("CellSize", resourceCulture);
            }
        }
        
        public static string DisableDefaultUOHotkeys {
            get {
                return ResourceManager.GetString("DisableDefaultUOHotkeys", resourceCulture);
            }
        }
        
        public static string DisableArrowsPlayerMovement {
            get {
                return ResourceManager.GetString("DisableArrowsPlayerMovement", resourceCulture);
            }
        }
        
        public static string DisableTab {
            get {
                return ResourceManager.GetString("DisableTab", resourceCulture);
            }
        }
        
        public static string DisableMessageHistory {
            get {
                return ResourceManager.GetString("DisableMessageHistory", resourceCulture);
            }
        }
        
        public static string DisableClickAutomove {
            get {
                return ResourceManager.GetString("DisableClickAutomove", resourceCulture);
            }
        }
        
        public static string ShowInfoBar {
            get {
                return ResourceManager.GetString("ShowInfoBar", resourceCulture);
            }
        }
        
        public static string DataHighlightType {
            get {
                return ResourceManager.GetString("DataHighlightType", resourceCulture);
            }
        }
        
        public static string TextColor {
            get {
                return ResourceManager.GetString("TextColor", resourceCulture);
            }
        }
        
        public static string ColoredBars {
            get {
                return ResourceManager.GetString("ColoredBars", resourceCulture);
            }
        }
        
        public static string AddItem {
            get {
                return ResourceManager.GetString("AddItem", resourceCulture);
            }
        }
        
        public static string Label {
            get {
                return ResourceManager.GetString("Label", resourceCulture);
            }
        }
        
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        public static string ContainerScale {
            get {
                return ResourceManager.GetString("ContainerScale", resourceCulture);
            }
        }
        
        public static string ScaleItemsInsideContainers {
            get {
                return ResourceManager.GetString("ScaleItemsInsideContainers", resourceCulture);
            }
        }
        
        public static string UseLargeContainersGump {
            get {
                return ResourceManager.GetString("UseLargeContainersGump", resourceCulture);
            }
        }
        
        public static string DoubleClickLootContainers {
            get {
                return ResourceManager.GetString("DoubleClickLootContainers", resourceCulture);
            }
        }
        
        public static string RelativeDragAndDropContainers {
            get {
                return ResourceManager.GetString("RelativeDragAndDropContainers", resourceCulture);
            }
        }
        
        public static string OverrideContainerGumpLocation {
            get {
                return ResourceManager.GetString("OverrideContainerGumpLocation", resourceCulture);
            }
        }
        
        public static string ContLoc_NearContainerPosition {
            get {
                return ResourceManager.GetString("ContLoc_NearContainerPosition", resourceCulture);
            }
        }
        
        public static string ContLoc_TopRight {
            get {
                return ResourceManager.GetString("ContLoc_TopRight", resourceCulture);
            }
        }
        
        public static string ContLoc_LastDraggedPosition {
            get {
                return ResourceManager.GetString("ContLoc_LastDraggedPosition", resourceCulture);
            }
        }
        
        public static string ContLoc_RememberEveryContainer {
            get {
                return ResourceManager.GetString("ContLoc_RememberEveryContainer", resourceCulture);
            }
        }
        
        public static string RebuildContainers {
            get {
                return ResourceManager.GetString("RebuildContainers", resourceCulture);
            }
        }
        
        public static string SpellFormat_Default {
            get {
                return ResourceManager.GetString("SpellFormat_Default", resourceCulture);
            }
        }
        
        public static string PartyAuraColor {
            get {
                return ResourceManager.GetString("PartyAuraColor", resourceCulture);
            }
        }
        
        public static string Counter_Rows {
            get {
                return ResourceManager.GetString("Counter_Rows", resourceCulture);
            }
        }
        
        public static string Counter_Columns {
            get {
                return ResourceManager.GetString("Counter_Columns", resourceCulture);
            }
        }
        
        public static string NoCityFound {
            get {
                return ResourceManager.GetString("NoCityFound", resourceCulture);
            }
        }
        
        public static string PermanentlyDelete0 {
            get {
                return ResourceManager.GetString("PermanentlyDelete0", resourceCulture);
            }
        }
        
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        public static string LoginToUO {
            get {
                return ResourceManager.GetString("LoginToUO", resourceCulture);
            }
        }
        
        public static string CUOVersion0 {
            get {
                return ResourceManager.GetString("CUOVersion0", resourceCulture);
            }
        }
        
        public static string Autologin {
            get {
                return ResourceManager.GetString("Autologin", resourceCulture);
            }
        }
        
        public static string SaveAccount {
            get {
                return ResourceManager.GetString("SaveAccount", resourceCulture);
            }
        }
        
        public static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        public static string BookPage0TooManyLines1Lost {
            get {
                return ResourceManager.GetString("BookPage0TooManyLines1Lost", resourceCulture);
            }
        }
        
        public static string BookPage0LineTooLong1 {
            get {
                return ResourceManager.GetString("BookPage0LineTooLong1", resourceCulture);
            }
        }
        
        public static string TimeLeft {
            get {
                return ResourceManager.GetString("TimeLeft", resourceCulture);
            }
        }
        
        public static string Span0Hours {
            get {
                return ResourceManager.GetString("Span0Hours", resourceCulture);
            }
        }
        
        public static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        public static string RE {
            get {
                return ResourceManager.GetString("RE", resourceCulture);
            }
        }
        
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        public static string PrimaryAbilityIcon {
            get {
                return ResourceManager.GetString("PrimaryAbilityIcon", resourceCulture);
            }
        }
        
        public static string SecondaryAbilityIcon {
            get {
                return ResourceManager.GetString("SecondaryAbilityIcon", resourceCulture);
            }
        }
        
        public static string IndexOutOfbounds {
            get {
                return ResourceManager.GetString("IndexOutOfbounds", resourceCulture);
            }
        }
        
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        public static string UseObject {
            get {
                return ResourceManager.GetString("UseObject", resourceCulture);
            }
        }
        
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        public static string Selected0 {
            get {
                return ResourceManager.GetString("Selected0", resourceCulture);
            }
        }
        
        public static string Static0Height1Flags2Alpha3 {
            get {
                return ResourceManager.GetString("Static0Height1Flags2Alpha3", resourceCulture);
            }
        }
        
        public static string GameEffect {
            get {
                return ResourceManager.GetString("GameEffect", resourceCulture);
            }
        }
        
        public static string TextOverheadType0Hue1 {
            get {
                return ResourceManager.GetString("TextOverheadType0Hue1", resourceCulture);
            }
        }
        
        public static string Land0Flags1 {
            get {
                return ResourceManager.GetString("Land0Flags1", resourceCulture);
            }
        }
        
        public static string SetLootBag {
            get {
                return ResourceManager.GetString("SetLootBag", resourceCulture);
            }
        }
        
        public static string Prev {
            get {
                return ResourceManager.GetString("Prev", resourceCulture);
            }
        }
        
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        public static string TargetContainerToGrabItemsInto {
            get {
                return ResourceManager.GetString("TargetContainerToGrabItemsInto", resourceCulture);
            }
        }
        
        public static string CorpseIsEmpty {
            get {
                return ResourceManager.GetString("CorpseIsEmpty", resourceCulture);
            }
        }
        
        public static string Self {
            get {
                return ResourceManager.GetString("Self", resourceCulture);
            }
        }
        
        public static string Walls {
            get {
                return ResourceManager.GetString("Walls", resourceCulture);
            }
        }
        
        public static string Doors {
            get {
                return ResourceManager.GetString("Doors", resourceCulture);
            }
        }
        
        public static string Floors {
            get {
                return ResourceManager.GetString("Floors", resourceCulture);
            }
        }
        
        public static string Stairs {
            get {
                return ResourceManager.GetString("Stairs", resourceCulture);
            }
        }
        
        public static string Roofs {
            get {
                return ResourceManager.GetString("Roofs", resourceCulture);
            }
        }
        
        public static string Miscellaneous {
            get {
                return ResourceManager.GetString("Miscellaneous", resourceCulture);
            }
        }
        
        public static string SystemMenu {
            get {
                return ResourceManager.GetString("SystemMenu", resourceCulture);
            }
        }
        
        public static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        public static string Erase {
            get {
                return ResourceManager.GetString("Erase", resourceCulture);
            }
        }
        
        public static string EyedropperTool {
            get {
                return ResourceManager.GetString("EyedropperTool", resourceCulture);
            }
        }
        
        public static string Store0Visibility {
            get {
                return ResourceManager.GetString("Store0Visibility", resourceCulture);
            }
        }
        
        public static string GoToStory0 {
            get {
                return ResourceManager.GetString("GoToStory0", resourceCulture);
            }
        }
        
        public static string PreviousPage {
            get {
                return ResourceManager.GetString("PreviousPage", resourceCulture);
            }
        }
        
        public static string NextPage {
            get {
                return ResourceManager.GetString("NextPage", resourceCulture);
            }
        }
        
        public static string ToCustomHouseManagerCategory {
            get {
                return ResourceManager.GetString("ToCustomHouseManagerCategory", resourceCulture);
            }
        }
        
        public static string WindowToggle {
            get {
                return ResourceManager.GetString("WindowToggle", resourceCulture);
            }
        }
        
        public static string LowerRoofPlacementLevel {
            get {
                return ResourceManager.GetString("LowerRoofPlacementLevel", resourceCulture);
            }
        }
        
        public static string RaiseRoofPlacementLevel {
            get {
                return ResourceManager.GetString("RaiseRoofPlacementLevel", resourceCulture);
            }
        }
        
        public static string Backup {
            get {
                return ResourceManager.GetString("Backup", resourceCulture);
            }
        }
        
        public static string StoreDesignInProgress {
            get {
                return ResourceManager.GetString("StoreDesignInProgress", resourceCulture);
            }
        }
        
        public static string RestoreYourDesign {
            get {
                return ResourceManager.GetString("RestoreYourDesign", resourceCulture);
            }
        }
        
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        public static string Sync {
            get {
                return ResourceManager.GetString("Sync", resourceCulture);
            }
        }
        
        public static string SynchronizeDesignStateWithServer {
            get {
                return ResourceManager.GetString("SynchronizeDesignStateWithServer", resourceCulture);
            }
        }
        
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        public static string ClearAllChanges {
            get {
                return ResourceManager.GetString("ClearAllChanges", resourceCulture);
            }
        }
        
        public static string Commit {
            get {
                return ResourceManager.GetString("Commit", resourceCulture);
            }
        }
        
        public static string SaveExistingChanges {
            get {
                return ResourceManager.GetString("SaveExistingChanges", resourceCulture);
            }
        }
        
        public static string Revert {
            get {
                return ResourceManager.GetString("Revert", resourceCulture);
            }
        }
        
        public static string RevertYourDesign {
            get {
                return ResourceManager.GetString("RevertYourDesign", resourceCulture);
            }
        }
        
        public static string ObjectInformation {
            get {
                return ResourceManager.GetString("ObjectInformation", resourceCulture);
            }
        }
        
        public static string Dump {
            get {
                return ResourceManager.GetString("Dump", resourceCulture);
            }
        }
        
        public static string DarkMode {
            get {
                return ResourceManager.GetString("DarkMode", resourceCulture);
            }
        }
        
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        public static string MobilesOnly {
            get {
                return ResourceManager.GetString("MobilesOnly", resourceCulture);
            }
        }
        
        public static string ItemsOnly {
            get {
                return ResourceManager.GetString("ItemsOnly", resourceCulture);
            }
        }
        
        public static string MobilesAndCorpsesOnly {
            get {
                return ResourceManager.GetString("MobilesAndCorpsesOnly", resourceCulture);
            }
        }
        
        public static string Tell {
            get {
                return ResourceManager.GetString("Tell", resourceCulture);
            }
        }
        
        public static string Kick {
            get {
                return ResourceManager.GetString("Kick", resourceCulture);
            }
        }
        
        public static string PartyManifest {
            get {
                return ResourceManager.GetString("PartyManifest", resourceCulture);
            }
        }
        
        public static string SendThePartyAMessage {
            get {
                return ResourceManager.GetString("SendThePartyAMessage", resourceCulture);
            }
        }
        
        public static string PartyCanLootMe {
            get {
                return ResourceManager.GetString("PartyCanLootMe", resourceCulture);
            }
        }
        
        public static string PartyCannotLootMe {
            get {
                return ResourceManager.GetString("PartyCannotLootMe", resourceCulture);
            }
        }
        
        public static string LeaveTheParty {
            get {
                return ResourceManager.GetString("LeaveTheParty", resourceCulture);
            }
        }
        
        public static string DisbandTheParty {
            get {
                return ResourceManager.GetString("DisbandTheParty", resourceCulture);
            }
        }
        
        public static string AddNewMember {
            get {
                return ResourceManager.GetString("AddNewMember", resourceCulture);
            }
        }
        
        public static string YouAreNotInAParty {
            get {
                return ResourceManager.GetString("YouAreNotInAParty", resourceCulture);
            }
        }
        
        public static string ThereIsNoOneInThatPartySlot {
            get {
                return ResourceManager.GetString("ThereIsNoOneInThatPartySlot", resourceCulture);
            }
        }
        
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        public static string Decline {
            get {
                return ResourceManager.GetString("Decline", resourceCulture);
            }
        }
        
        public static string P0HasInvitedYouToParty {
            get {
                return ResourceManager.GetString("P0HasInvitedYouToParty", resourceCulture);
            }
        }
        
        public static string NoName {
            get {
                return ResourceManager.GetString("NoName", resourceCulture);
            }
        }
        
        public static string Passive {
            get {
                return ResourceManager.GetString("Passive", resourceCulture);
            }
        }
        
        public static string Item0Price1 {
            get {
                return ResourceManager.GetString("Item0Price1", resourceCulture);
            }
        }
        
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        public static string Real {
            get {
                return ResourceManager.GetString("Real", resourceCulture);
            }
        }
        
        public static string Base {
            get {
                return ResourceManager.GetString("Base", resourceCulture);
            }
        }
        
        public static string Cap {
            get {
                return ResourceManager.GetString("Cap", resourceCulture);
            }
        }
        
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        public static string TithingPointsAvailable {
            get {
                return ResourceManager.GetString("TithingPointsAvailable", resourceCulture);
            }
        }
        
        public static string Abilities {
            get {
                return ResourceManager.GetString("Abilities", resourceCulture);
            }
        }
        
        public static string Activated {
            get {
                return ResourceManager.GetString("Activated", resourceCulture);
            }
        }
        
        public static string Reagents {
            get {
                return ResourceManager.GetString("Reagents", resourceCulture);
            }
        }
        
        public static string Upkeep0Mana1MinSkill2 {
            get {
                return ResourceManager.GetString("Upkeep0Mana1MinSkill2", resourceCulture);
            }
        }
        
        public static string ManaCost0MinSkill1 {
            get {
                return ResourceManager.GetString("ManaCost0MinSkill1", resourceCulture);
            }
        }
        
        public static string ShowReal {
            get {
                return ResourceManager.GetString("ShowReal", resourceCulture);
            }
        }
        
        public static string ShowCaps {
            get {
                return ResourceManager.GetString("ShowCaps", resourceCulture);
            }
        }
        
        public static string NewGroup {
            get {
                return ResourceManager.GetString("NewGroup", resourceCulture);
            }
        }
        
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        public static string Buffs {
            get {
                return ResourceManager.GetString("Buffs", resourceCulture);
            }
        }
        
        public static string Whisper {
            get {
                return ResourceManager.GetString("Whisper", resourceCulture);
            }
        }
        
        public static string Emote {
            get {
                return ResourceManager.GetString("Emote", resourceCulture);
            }
        }
        
        public static string Yell {
            get {
                return ResourceManager.GetString("Yell", resourceCulture);
            }
        }
        
        public static string Party {
            get {
                return ResourceManager.GetString("Party", resourceCulture);
            }
        }
        
        public static string Guild {
            get {
                return ResourceManager.GetString("Guild", resourceCulture);
            }
        }
        
        public static string Alliance {
            get {
                return ResourceManager.GetString("Alliance", resourceCulture);
            }
        }
        
        public static string Command {
            get {
                return ResourceManager.GetString("Command", resourceCulture);
            }
        }
        
        public static string UOAM {
            get {
                return ResourceManager.GetString("UOAM", resourceCulture);
            }
        }
        
        public static string Chat {
            get {
                return ResourceManager.GetString("Chat", resourceCulture);
            }
        }
        
        public static string PartyName0Text1 {
            get {
                return ResourceManager.GetString("PartyName0Text1", resourceCulture);
            }
        }
        
        public static string GuildName0Text1 {
            get {
                return ResourceManager.GetString("GuildName0Text1", resourceCulture);
            }
        }
        
        public static string AllianceName0Text1 {
            get {
                return ResourceManager.GetString("AllianceName0Text1", resourceCulture);
            }
        }
        
        public static string Tell0 {
            get {
                return ResourceManager.GetString("Tell0", resourceCulture);
            }
        }
        
        public static string TellEmpty {
            get {
                return ResourceManager.GetString("TellEmpty", resourceCulture);
            }
        }
        
        public static string YouAreNotPartyLeader {
            get {
                return ResourceManager.GetString("YouAreNotPartyLeader", resourceCulture);
            }
        }
        
        public static string NoOneHasInvitedYouToBeInAParty {
            get {
                return ResourceManager.GetString("NoOneHasInvitedYouToBeInAParty", resourceCulture);
            }
        }
        
        public static string NoteToSelf0 {
            get {
                return ResourceManager.GetString("NoteToSelf0", resourceCulture);
            }
        }
        
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        public static string Paperdoll {
            get {
                return ResourceManager.GetString("Paperdoll", resourceCulture);
            }
        }
        
        public static string Inventory {
            get {
                return ResourceManager.GetString("Inventory", resourceCulture);
            }
        }
        
        public static string Journal {
            get {
                return ResourceManager.GetString("Journal", resourceCulture);
            }
        }
        
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        public static string WorldMap {
            get {
                return ResourceManager.GetString("WorldMap", resourceCulture);
            }
        }
        
        public static string Debug {
            get {
                return ResourceManager.GetString("Debug", resourceCulture);
            }
        }
        
        public static string NetStats {
            get {
                return ResourceManager.GetString("NetStats", resourceCulture);
            }
        }
        
        public static string UOStore {
            get {
                return ResourceManager.GetString("UOStore", resourceCulture);
            }
        }
        
        public static string GlobalChat {
            get {
                return ResourceManager.GetString("GlobalChat", resourceCulture);
            }
        }
        
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        public static string TopBarGumpAlreadyExists {
            get {
                return ResourceManager.GetString("TopBarGumpAlreadyExists", resourceCulture);
            }
        }
        
        public static string ChatButtonPushedNotImplementedYet {
            get {
                return ResourceManager.GetString("ChatButtonPushedNotImplementedYet", resourceCulture);
            }
        }
        
        public static string GlobalChatNotImplementedYet {
            get {
                return ResourceManager.GetString("GlobalChatNotImplementedYet", resourceCulture);
            }
        }
        
        public static string ChooseName {
            get {
                return ResourceManager.GetString("ChooseName", resourceCulture);
            }
        }
        
        public static string Channels {
            get {
                return ResourceManager.GetString("Channels", resourceCulture);
            }
        }
        
        public static string YourCurrentChannel {
            get {
                return ResourceManager.GetString("YourCurrentChannel", resourceCulture);
            }
        }
        
        public static string Join {
            get {
                return ResourceManager.GetString("Join", resourceCulture);
            }
        }
        
        public static string Leave {
            get {
                return ResourceManager.GetString("Leave", resourceCulture);
            }
        }
        
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        public static string CreateAChannel {
            get {
                return ResourceManager.GetString("CreateAChannel", resourceCulture);
            }
        }
        
        public static string WorldMapLoading {
            get {
                return ResourceManager.GetString("WorldMapLoading", resourceCulture);
            }
        }
        
        public static string ShowAllMarkers {
            get {
                return ResourceManager.GetString("ShowAllMarkers", resourceCulture);
            }
        }
        
        public static string ShowMarkerNames {
            get {
                return ResourceManager.GetString("ShowMarkerNames", resourceCulture);
            }
        }
        
        public static string ShowMarkerIcons {
            get {
                return ResourceManager.GetString("ShowMarkerIcons", resourceCulture);
            }
        }
        
        public static string FlipMap {
            get {
                return ResourceManager.GetString("FlipMap", resourceCulture);
            }
        }
        
        public static string TopMost {
            get {
                return ResourceManager.GetString("TopMost", resourceCulture);
            }
        }
        
        public static string GotoLocation {
            get {
                return ResourceManager.GetString("GotoLocation", resourceCulture);
            }
        }
        
        public static string EnterLocation {
            get {
                return ResourceManager.GetString("EnterLocation", resourceCulture);
            }
        }
        
        public static string InvalidLocation {
            get {
                return ResourceManager.GetString("InvalidLocation", resourceCulture);
            }
        }
        
        public static string FreeView {
            get {
                return ResourceManager.GetString("FreeView", resourceCulture);
            }
        }
        
        public static string ShowPartyMembers {
            get {
                return ResourceManager.GetString("ShowPartyMembers", resourceCulture);
            }
        }
        
        public static string ShowMobiles {
            get {
                return ResourceManager.GetString("ShowMobiles", resourceCulture);
            }
        }
        
        public static string ShowHousesBoats {
            get {
                return ResourceManager.GetString("ShowHousesBoats", resourceCulture);
            }
        }
        
        public static string ShowYourName {
            get {
                return ResourceManager.GetString("ShowYourName", resourceCulture);
            }
        }
        
        public static string ShowYourHealthbar {
            get {
                return ResourceManager.GetString("ShowYourHealthbar", resourceCulture);
            }
        }
        
        public static string ShowGroupName {
            get {
                return ResourceManager.GetString("ShowGroupName", resourceCulture);
            }
        }
        
        public static string ShowGroupHealthbar {
            get {
                return ResourceManager.GetString("ShowGroupHealthbar", resourceCulture);
            }
        }
        
        public static string ShowYourCoordinates {
            get {
                return ResourceManager.GetString("ShowYourCoordinates", resourceCulture);
            }
        }
        
        public static string SaveClose {
            get {
                return ResourceManager.GetString("SaveClose", resourceCulture);
            }
        }
        
        public static string FontStyle {
            get {
                return ResourceManager.GetString("FontStyle", resourceCulture);
            }
        }
        
        public static string Style0 {
            get {
                return ResourceManager.GetString("Style0", resourceCulture);
            }
        }
        
        public static string MapMarkerOptions {
            get {
                return ResourceManager.GetString("MapMarkerOptions", resourceCulture);
            }
        }
        
        public static string ReloadMarkers {
            get {
                return ResourceManager.GetString("ReloadMarkers", resourceCulture);
            }
        }
        
        public static string ShowHide0 {
            get {
                return ResourceManager.GetString("ShowHide0", resourceCulture);
            }
        }
        
        public static string NoMapFiles {
            get {
                return ResourceManager.GetString("NoMapFiles", resourceCulture);
            }
        }
        
        public static string NamesHealthbars {
            get {
                return ResourceManager.GetString("NamesHealthbars", resourceCulture);
            }
        }
        
        public static string WorldMapLoaded {
            get {
                return ResourceManager.GetString("WorldMapLoaded", resourceCulture);
            }
        }
        
        public static string LoadingWorldMapMarkers {
            get {
                return ResourceManager.GetString("LoadingWorldMapMarkers", resourceCulture);
            }
        }
        
        public static string WorldMapMarkersLoaded0 {
            get {
                return ResourceManager.GetString("WorldMapMarkersLoaded0", resourceCulture);
            }
        }
        
        public static string OutOfRange {
            get {
                return ResourceManager.GetString("OutOfRange", resourceCulture);
            }
        }
        
        public static string ResizeGameWindow {
            get {
                return ResourceManager.GetString("ResizeGameWindow", resourceCulture);
            }
        }
        
        public static string KeyCombinationAlreadyExists {
            get {
                return ResourceManager.GetString("KeyCombinationAlreadyExists", resourceCulture);
            }
        }
        
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        public static string CreateMacroButton {
            get {
                return ResourceManager.GetString("CreateMacroButton", resourceCulture);
            }
        }
        
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        public static string ThisKeyCombinationAlreadyExists {
            get {
                return ResourceManager.GetString("ThisKeyCombinationAlreadyExists", resourceCulture);
            }
        }
        
        public static string ImpossibleToDefineTheClientVersion0 {
            get {
                return ResourceManager.GetString("ImpossibleToDefineTheClientVersion0", resourceCulture);
            }
        }
        
        public static string SelectWhichShardToPlayOn {
            get {
                return ResourceManager.GetString("SelectWhichShardToPlayOn", resourceCulture);
            }
        }
        
        public static string Latency {
            get {
                return ResourceManager.GetString("Latency", resourceCulture);
            }
        }
        
        public static string PacketLoss {
            get {
                return ResourceManager.GetString("PacketLoss", resourceCulture);
            }
        }
        
        public static string SortBy {
            get {
                return ResourceManager.GetString("SortBy", resourceCulture);
            }
        }
        
        public static string Localisation {
            get {
                return ResourceManager.GetString("Localisation", resourceCulture);
            }
        }
        
        public static string ChangingLanguageNeedsRestartToTakeEffect {
            get {
                return ResourceManager.GetString("ChangingLanguageNeedsRestartToTakeEffect", resourceCulture);
            }
        }
        
        public static string Strength {
            get {
                return ResourceManager.GetString("Strength", resourceCulture);
            }
        }
        
        public static string Dex {
            get {
                return ResourceManager.GetString("Dex", resourceCulture);
            }
        }
        
        public static string Intelligence {
            get {
                return ResourceManager.GetString("Intelligence", resourceCulture);
            }
        }
        
        public static string Sex {
            get {
                return ResourceManager.GetString("Sex", resourceCulture);
            }
        }
        
        public static string Armor {
            get {
                return ResourceManager.GetString("Armor", resourceCulture);
            }
        }
        
        public static string Stamina {
            get {
                return ResourceManager.GetString("Stamina", resourceCulture);
            }
        }
        
        public static string Gold {
            get {
                return ResourceManager.GetString("Gold", resourceCulture);
            }
        }
        
        public static string HitChanceIncrease {
            get {
                return ResourceManager.GetString("HitChanceIncrease", resourceCulture);
            }
        }
        
        public static string Dexterity {
            get {
                return ResourceManager.GetString("Dexterity", resourceCulture);
            }
        }
        
        public static string DefenseChanceIncrease {
            get {
                return ResourceManager.GetString("DefenseChanceIncrease", resourceCulture);
            }
        }
        
        public static string HitPoints {
            get {
                return ResourceManager.GetString("HitPoints", resourceCulture);
            }
        }
        
        public static string LowerManaCost {
            get {
                return ResourceManager.GetString("LowerManaCost", resourceCulture);
            }
        }
        
        public static string MaximumStats {
            get {
                return ResourceManager.GetString("MaximumStats", resourceCulture);
            }
        }
        
        public static string Luck {
            get {
                return ResourceManager.GetString("Luck", resourceCulture);
            }
        }
        
        public static string WeaponDamageIncrease {
            get {
                return ResourceManager.GetString("WeaponDamageIncrease", resourceCulture);
            }
        }
        
        public static string SwingSpeedIncrease {
            get {
                return ResourceManager.GetString("SwingSpeedIncrease", resourceCulture);
            }
        }
        
        public static string Damage {
            get {
                return ResourceManager.GetString("Damage", resourceCulture);
            }
        }
        
        public static string Followers {
            get {
                return ResourceManager.GetString("Followers", resourceCulture);
            }
        }
        
        public static string LowerReagentCost {
            get {
                return ResourceManager.GetString("LowerReagentCost", resourceCulture);
            }
        }
        
        public static string SpellDamageIncrease {
            get {
                return ResourceManager.GetString("SpellDamageIncrease", resourceCulture);
            }
        }
        
        public static string FasterCasting {
            get {
                return ResourceManager.GetString("FasterCasting", resourceCulture);
            }
        }
        
        public static string FasterCastRecovery {
            get {
                return ResourceManager.GetString("FasterCastRecovery", resourceCulture);
            }
        }
        
        public static string PhysicalResistance {
            get {
                return ResourceManager.GetString("PhysicalResistance", resourceCulture);
            }
        }
        
        public static string FireResistance {
            get {
                return ResourceManager.GetString("FireResistance", resourceCulture);
            }
        }
        
        public static string ColdResistance {
            get {
                return ResourceManager.GetString("ColdResistance", resourceCulture);
            }
        }
        
        public static string PoisonResistance {
            get {
                return ResourceManager.GetString("PoisonResistance", resourceCulture);
            }
        }
        
        public static string EnergyResistance {
            get {
                return ResourceManager.GetString("EnergyResistance", resourceCulture);
            }
        }
        
        public static string MaxStats {
            get {
                return ResourceManager.GetString("MaxStats", resourceCulture);
            }
        }
        
        public static string Minimize {
            get {
                return ResourceManager.GetString("Minimize", resourceCulture);
            }
        }
        
        public static string HideScreenshotStoredInMessage {
            get {
                return ResourceManager.GetString("HideScreenshotStoredInMessage", resourceCulture);
            }
        }
        
        public static string AnisotropicClamp {
            get {
                return ResourceManager.GetString("AnisotropicClamp", resourceCulture);
            }
        }
        
        public static string FilterType {
            get {
                return ResourceManager.GetString("FilterType", resourceCulture);
            }
        }
        
        public static string FilterTypeFormatON {
            get {
                return ResourceManager.GetString("FilterTypeFormatON", resourceCulture);
            }
        }
        
        public static string LinearClamp {
            get {
                return ResourceManager.GetString("LinearClamp", resourceCulture);
            }
        }
        
        public static string OFF {
            get {
                return ResourceManager.GetString("OFF", resourceCulture);
            }
        }
        
        public static string ON {
            get {
                return ResourceManager.GetString("ON", resourceCulture);
            }
        }
        
        public static string HighlightContainerWhenSelected {
            get {
                return ResourceManager.GetString("HighlightContainerWhenSelected", resourceCulture);
            }
        }
        
        public static string YouMustHaveThreeUniqueSkillsChosen {
            get {
                return ResourceManager.GetString("YouMustHaveThreeUniqueSkillsChosen", resourceCulture);
            }
        }
        
        public static string ShowSkillsChangedMessageBy {
            get {
                return ResourceManager.GetString("ShowSkillsChangedMessageBy", resourceCulture);
            }
        }
        
        public static string ShowStatsChangedMessage {
            get {
                return ResourceManager.GetString("ShowStatsChangedMessage", resourceCulture);
            }
        }
        
        public static string ShadowStatics {
            get {
                return ResourceManager.GetString("ShadowStatics", resourceCulture);
            }
        }
        
        public static string BackpackStyle {
            get {
                return ResourceManager.GetString("BackpackStyle", resourceCulture);
            }
        }
        
        public static string BackpackStyle_Default {
            get {
                return ResourceManager.GetString("BackpackStyle_Default", resourceCulture);
            }
        }
        
        public static string BackpackStyle_Suede {
            get {
                return ResourceManager.GetString("BackpackStyle_Suede", resourceCulture);
            }
        }
        
        public static string BackpackStyle_PolarBear {
            get {
                return ResourceManager.GetString("BackpackStyle_PolarBear", resourceCulture);
            }
        }
        
        public static string BackpackStyle_GhoulSkin {
            get {
                return ResourceManager.GetString("BackpackStyle_GhoulSkin", resourceCulture);
            }
        }
        
        public static string ResetGroups {
            get {
                return ResourceManager.GetString("ResetGroups", resourceCulture);
            }
        }
        
        public static string TerrainShadowsLevel {
            get {
                return ResourceManager.GetString("TerrainShadowsLevel", resourceCulture);
            }
        }
        
        public static string IgnoreGuildMessages {
            get {
                return ResourceManager.GetString("IgnoreGuildMessages", resourceCulture);
            }
        }
        
        public static string IgnoreAllianceMessages {
            get {
                return ResourceManager.GetString("IgnoreAllianceMessages", resourceCulture);
            }
        }
        
        public static string OpenMacroSettings {
            get {
                return ResourceManager.GetString("OpenMacroSettings", resourceCulture);
            }
        }
        
        public static string EnableFastSpellsAssign {
            get {
                return ResourceManager.GetString("EnableFastSpellsAssign", resourceCulture);
            }
        }
        
        public static string HighlightInvulnerable {
            get {
                return ResourceManager.GetString("HighlightInvulnerable", resourceCulture);
            }
        }
        
        public static string HighlightParalyzed {
            get {
                return ResourceManager.GetString("HighlightParalyzed", resourceCulture);
            }
        }
        
        public static string HighlightPoisoned {
            get {
                return ResourceManager.GetString("HighlightPoisoned", resourceCulture);
            }
        }
        
        public static string AddMarkerOnPlayer {
            get {
                return ResourceManager.GetString("AddMarkerOnPlayer", resourceCulture);
            }
        }
        
        public static string EnterMarkerName {
            get {
                return ResourceManager.GetString("EnterMarkerName", resourceCulture);
            }
        }
        
        public static string InvalidMarkerName {
            get {
                return ResourceManager.GetString("InvalidMarkerName", resourceCulture);
            }
        }
        
        public static string AddToIgnoreListExist {
            get {
                return ResourceManager.GetString("AddToIgnoreListExist", resourceCulture);
            }
        }
        
        public static string AddToIgnoreListNotMobile {
            get {
                return ResourceManager.GetString("AddToIgnoreListNotMobile", resourceCulture);
            }
        }
        
        public static string AddToIgnoreListSuccess {
            get {
                return ResourceManager.GetString("AddToIgnoreListSuccess", resourceCulture);
            }
        }
        
        public static string IgnoreListAddButton {
            get {
                return ResourceManager.GetString("IgnoreListAddButton", resourceCulture);
            }
        }
        
        public static string IgnoreListManager {
            get {
                return ResourceManager.GetString("IgnoreListManager", resourceCulture);
            }
        }
        
        public static string IgnoreListName {
            get {
                return ResourceManager.GetString("IgnoreListName", resourceCulture);
            }
        }
        
        public static string AddMarker {
            get {
                return ResourceManager.GetString("AddMarker", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string CreateMarker {
            get {
                return ResourceManager.GetString("CreateMarker", resourceCulture);
            }
        }
        
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        public static string EditMarker {
            get {
                return ResourceManager.GetString("EditMarker", resourceCulture);
            }
        }
        
        public static string MarkerColor {
            get {
                return ResourceManager.GetString("MarkerColor", resourceCulture);
            }
        }
        
        public static string MarkerDefName {
            get {
                return ResourceManager.GetString("MarkerDefName", resourceCulture);
            }
        }
        
        public static string MarkerGoTo {
            get {
                return ResourceManager.GetString("MarkerGoTo", resourceCulture);
            }
        }
        
        public static string MarkerIcon {
            get {
                return ResourceManager.GetString("MarkerIcon", resourceCulture);
            }
        }
        
        public static string MarkerName {
            get {
                return ResourceManager.GetString("MarkerName", resourceCulture);
            }
        }
        
        public static string MarkerSearch {
            get {
                return ResourceManager.GetString("MarkerSearch", resourceCulture);
            }
        }
        
        public static string MarkersManager {
            get {
                return ResourceManager.GetString("MarkersManager", resourceCulture);
            }
        }
        
        public static string MarkerX {
            get {
                return ResourceManager.GetString("MarkerX", resourceCulture);
            }
        }
        
        public static string MarkerY {
            get {
                return ResourceManager.GetString("MarkerY", resourceCulture);
            }
        }
        
        public static string DragSelectAnchoredHB {
            get {
                return ResourceManager.GetString("DragSelectAnchoredHB", resourceCulture);
            }
        }
        
        public static string DragSelectStartingPosX {
            get {
                return ResourceManager.GetString("DragSelectStartingPosX", resourceCulture);
            }
        }
        
        public static string DragSelectStartingPosY {
            get {
                return ResourceManager.GetString("DragSelectStartingPosY", resourceCulture);
            }
        }
        
        public static string MapZoneFileName {
            get {
                return ResourceManager.GetString("MapZoneFileName", resourceCulture);
            }
        }
        
        public static string MapZoneNone {
            get {
                return ResourceManager.GetString("MapZoneNone", resourceCulture);
            }
        }
        
        public static string MapZoneOptions {
            get {
                return ResourceManager.GetString("MapZoneOptions", resourceCulture);
            }
        }
        
        public static string MapZoneReload {
            get {
                return ResourceManager.GetString("MapZoneReload", resourceCulture);
            }
        }
        
        public static string MapZoneFileLoaded {
            get {
                return ResourceManager.GetString("MapZoneFileLoaded", resourceCulture);
            }
        }
        
        public static string GridIfZoomed {
            get {
                return ResourceManager.GetString("GridIfZoomed", resourceCulture);
            }
        }
        
        public static string ShowMouseCoordinates {
            get {
                return ResourceManager.GetString("ShowMouseCoordinates", resourceCulture);
            }
        }
        
        public static string AllowPositionalTargeting {
            get {
                return ResourceManager.GetString("AllowPositionalTargeting", resourceCulture);
            }
        }
        
        public static string LightLevelType {
            get {
                return ResourceManager.GetString("LightLevelType", resourceCulture);
            }
        }
        
        public static string LightLevelTypeAbsolute {
            get {
                return ResourceManager.GetString("LightLevelTypeAbsolute", resourceCulture);
            }
        }
        
        public static string LightLevelTypeMinimum {
            get {
                return ResourceManager.GetString("LightLevelTypeMinimum", resourceCulture);
            }
        }
        
        public static string HueContainerGumps {
            get {
                return ResourceManager.GetString("HueContainerGumps", resourceCulture);
            }
        }
        
        public static string ResetMapsCache {
            get {
                return ResourceManager.GetString("ResetMapsCache", resourceCulture);
            }
        }
        
        public static string NewTargetSystem {
            get {
                return ResourceManager.GetString("NewTargetSystem", resourceCulture);
            }
        }
        
        public static string ShowSextantCoordinates {
            get {
                return ResourceManager.GetString("ShowSextantCoordinates", resourceCulture);
            }
        }
        
        public static string WorldMapChangeMap0 {
            get {
                return ResourceManager.GetString("WorldMapChangeMap0", resourceCulture);
            }
        }
        
        public static string StatusGumpBarMutuallyExclusive {
            get {
                return ResourceManager.GetString("StatusGumpBarMutuallyExclusive", resourceCulture);
            }
        }
        
        public static string StatusGumpOpenBar {
            get {
                return ResourceManager.GetString("StatusGumpOpenBar", resourceCulture);
            }
        }
        
        public static string DragHostileOnly {
            get {
                return ResourceManager.GetString("DragHostileOnly", resourceCulture);
            }
        }
    }
}
