name: Build

on:
  workflow_dispatch

env:
  DOTNET_NOLOGO: false
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  NUGET_XMLDOC_MODE: skip

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
       os: [ macos-latest, ubuntu-latest, windows-latest ]

    steps:
    - uses: actions/checkout@v2
      
    - name: Install FNA
      run: git submodule update --init --recursive
        
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
            
    - name: Build
      run: dotnet build -c Release
      
    - name: Test
      run: dotnet test --verbosity normal
      
    - name: Zip Razor
      id: create_zip
      uses: papeloto/action-zip@v1
      with:
        files: bin\Release\ClassicUO.exe
        recursive: false
        dest: ClassicUO-${{ steps.get_version.outputs.version }}.zip

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: "v${{steps.get_version.outputs.version}}"
        release_name: ClassicUO ${{steps.get_version.outputs.version}}
        draft: false
        prerelease: false

    - name: Deploy        
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./ClassicUO-${{ steps.get_version.outputs.version }}.zip
        asset_name: ClassicUO-${{ steps.get_version.outputs.version }}.zip
        asset_content_type: application/zip
